<?php
$frm_apellido_paterno = @@frm_apellido_paterno ;
$frm_apellido_materno = @@frm_apellido_materno ;
$frm_primer_nombre = @@frm_primer_nombre ;
$frm_segundo_nombre = @@frm_segundo_nombre ;
$frm_tipo_identificacion_label = @@frm_tipo_identificacion_label ;
$frm_numero_identificacion = @@frm_numero_identificacion ;
$frm_lugar_residencia_habitual_label = @@frm_lugar_residencia_habitual_label ;
$frm_pais_nacimiento_label = @@frm_pais_nacimiento_label ;
$frm_ocupacion_profesion_label = @@frm_ocupacion_profesion_label ;
$frm_ocupacion_tipo_empleo_label = @@frm_ocupacion_tipo_empleo_label ;
$frm_ciudad_nacimiento_label = @@frm_ciudad_nacimiento_label ;
$frm_fecha_nacimiento = @@frm_fecha_nacimiento ;
$frm_nacionalidad_label = @@frm_nacionalidad_label ;
$frm_sexo_label = @@frm_sexo_label ;
$frm_estado_civil_label = @@frm_estado_civil_label ;
$frm_numero_hijos = @@frm_numero_hijos ;
$frm_provincia_label = @@frm_provincia_label ;
$frm_canton_label = @@frm_canton_label ;
$frm_barrio = @@frm_barrio ;
$frm_calle_principal = @@frm_calle_principal ;
$frm_numero = @@frm_numero ;
$frm_calle_transversal = @@frm_calle_transversal ;
$frm_conjunto_edificio = @@frm_conjunto_edificio ;
$frm_departamento_casa = @@frm_departamento_casa ;
$frm_codigo_provincia = @@frm_codigo_provincia ;
$frm_convencional = @@frm_convencional ;
$frm_celular = @@frm_celular ;
$frm_hora_inicial_label = @@frm_hora_inicial_label ;
$frm_hora_final_label = @@frm_hora_final_label ;
$frm_correo_electronico_personal = @@frm_correo_electronico_personal ;
$frm_ocupacion_mayor_ingresos_label = @@frm_ocupacion_mayor_ingresos_label ;
$frm_ocupacion_tipo_label = @@frm_ocupacion_tipo_label ;
$frm_ocupacion_otras_ocupaciones = @@frm_ocupacion_otras_ocupaciones ;
$frm_trabajo_provincia_label = @@frm_trabajo_provincia_label ;
$frm_trabajo_canton_label = @@frm_trabajo_canton_label ;
$frm_trabajo_sector_barrio = @@frm_trabajo_sector_barrio ;
$frm_trabajo_calle_principal = @@frm_trabajo_calle_principal ;
$frm_trabajo_numero = @@frm_trabajo_numero ;
$frm_trabajo_calle_transversal = @@frm_trabajo_calle_transversal ;
$frm_trabajo_edificio = @@frm_trabajo_edificio ;
$frm_trabajo_oficina = @@frm_trabajo_oficina ;
$frm_trabajo_codigo_provincia = @@frm_trabajo_codigo_provincia ;
$frm_trabajo_convencional = @@frm_trabajo_convencional ;
$frm_trabajo_celular = @@frm_trabajo_celular ;
$frm_trabajo_hora_inicial_label = @@frm_trabajo_hora_inicial_label ;
$frm_trabajo_hora_final_label = @@frm_trabajo_hora_final_label ;
$frm_trabajo_correo_trabajo_label = @@frm_trabajo_correo_trabajo_label ;
$frm_relacion_ocupacion_habitual_label = @@frm_relacion_ocupacion_habitual_label ;
$frm_frecuencia_viajes = @@frm_frecuencia_viajes ;
$frm_otra_actividad_relacion_habitual = @@frm_otra_actividad_relacion_habitual ;
$frm_actividades_trabajo_diario = @@frm_actividades_trabajo_diario ;
$frm_deporte_practica_label = @@frm_deporte_practica_label ;
$frm_tipo_practica_deporte_label = @@frm_tipo_practica_deporte_label ;
$frm_conduce_moto_label = @@frm_conduce_moto_label ;
$frm_cilindraje_moto = @@frm_cilindraje_moto ;
$frm_tipo_uso_moto = @@frm_tipo_uso_moto ;
$frm_tiene_accidentes_label = @@frm_tiene_accidentes_label ;
$frm_fecha_accidentes = @@frm_fecha_accidentes ;
$frm_gravedad_accidente = @@frm_gravedad_accidente ;
$frm_piloto_label = @@frm_piloto_label ;
$frm_trabajo_expuesta_politicamente_label = @@frm_trabajo_expuesta_politicamente_label ;
$frm_expuesta_especifique_label = @@frm_expuesta_especifique_label ;
$frm_referencia_personal_nombre = @@frm_referencia_personal_nombre ;
$frm_referencia_personal_telefono = @@frm_referencia_personal_telefono ;
$frm_referencia_comercial_nombre = @@frm_referencia_comercial_nombre ;
$frm_referencia_comercial_telefono = @@frm_referencia_comercial_telefono ;
$frm_referencia_bancaria_nombre_label = @@frm_referencia_bancaria_nombre_label ;
$frm_referencia_bancaria_tipo_label = @@frm_referencia_bancaria_tipo_label ;
$frm_referencia_bancaria_numero = @@frm_referencia_bancaria_numero ;
$frm_financiera_actividad_principal = @@frm_financiera_actividad_principal ;
$frm_financiera_otros_ingresos_temp = @@frm_financiera_otros_ingresos_temp ;
$frm_ingresos_familiares = @@frm_ingresos_familiares ;
$frm_origen_otros_ingresos_temp = @@frm_origen_otros_ingresos_temp ;
$frm_financiera_total_ingresos = @@frm_financiera_total_ingresos ;
$frm_financiera_total_egresos = @@frm_financiera_total_egresos ;
$frm_financiera_total_activos = @@frm_financiera_total_activos ;
$frm_financiera_total_pasivos = @@frm_financiera_total_pasivos ;
$frm_ingresos_ultimo_anio = @@frm_ingresos_ultimo_anio ;
$frm_ingresos_anterior_anio = @@frm_ingresos_anterior_anio ;
$frm_motivo_seguro_label = @@frm_motivo_seguro_label ;
$frm_nombre_hijos = @@frm_nombre_hijos ;
$frm_tipo_seguro_contratado_label = @@frm_tipo_seguro_contratado_label ;
$frm_incluye_dental_label = @@frm_incluye_dental_label ;
$frm_valor_asegurado = @@frm_valor_asegurado ;
$frm_prima_total = @@frm_prima_total ;
$frm_frecuencia_pago = @@frm_frecuencia_pago ;
$frm_plan_numero_identificacion_beneficiario = @@frm_plan_numero_identificacion_beneficiario ;
$frm_polizaanombrede = @@frm_polizaanombrede ;
$frm_plan_primer_nombre_label = @@frm_plan_primer_nombre_label ;
$frm_plan_segundo_nombre_label = @@frm_plan_segundo_nombre_label ;
$frm_plan_primer_apellido_label = @@frm_plan_primer_apellido_label ;
$frm_plan_segundo_apellido_label = @@frm_plan_segundo_apellido_label ;
$frm_plan_prentesco_label = @@frm_plan_prentesco_label ;
$frm_plan_porcentaje_label = @@frm_plan_porcentaje_label ;
$frm_plan_numero_identificacion_beneficiario_contingente = @@frm_plan_numero_identificacion_beneficiario_contingente ;
$frm_plan_primer_nombre_contingente = @@frm_plan_primer_nombre_contingente ;
$frm_plan_segundo_nombre_contingente = @@frm_plan_segundo_nombre_contingente ;
$frm_plan_primer_apellido_contingente = @@frm_plan_primer_apellido_contingente ;
$frm_plan_segundo_apellido_contingente = @@frm_plan_segundo_apellido_contingente ;
$frm_plan_prentesco_contingente_label = @@frm_plan_prentesco_contingente_label ;
$frm_plan_porcentaje_contingente = @@frm_plan_porcentaje_contingente ;
$frm_dental_identificacion = @@frm_dental_identificacion ;
$frm_dental_primer_nombre = @@frm_dental_primer_nombre ;
$frm_dental_segundo_nombre = @@frm_dental_segundo_nombre ;
$frm_dental_primer_apellido = @@frm_dental_primer_apellido ;
$frm_dental_segundo_apellido = @@frm_dental_segundo_apellido ;
$frm_dental_parentesco_label = @@frm_dental_parentesco_label ;
$frm_dental_fecha_nacimiento = @@frm_dental_fecha_nacimiento ;
$frm_plan_relacion_label = @@frm_plan_relacion_label ;
$frm_plan_tipo_relacion_label = @@frm_plan_tipo_relacion_label ;
$frm_plan_otra_label = @@frm_plan_otra_label ;
$frm_opcion_liquidacion_valor_label = @@frm_opcion_liquidacion_valor_label ;
$frm_plazo_cuotas_liquidacion_temp = @@frm_plazo_cuotas_liquidacion_temp ;
$frm_pago_unico_porcentaje_temp = @@frm_pago_unico_porcentaje_temp ;
$frm_pago_cuota_porcentaje_temp = @@frm_pago_cuota_porcentaje_temp ;
$frm_plazo_cuotas_liquidacion_combinada_temp = @@frm_plazo_cuotas_liquidacion_combinada_temp ;
$frm_ramooplan_label = @@frm_ramooplan_label ;
$frm_compania = @@frm_compania ;
$frm_valor_asegurado_otros = @@frm_valor_asegurado_otros ;
$frm_solicitud_seguro_vegente_label = @@frm_solicitud_seguro_vegente_label ;
$frm_solicitud_extraprima_label = @@frm_solicitud_extraprima_label ;
$frm_seguro_negado_label = @@frm_seguro_negado_label ;

$frm_causa_negacion_temp = @@frm_causa_negacion_temp ;
$frm_declaracion_peso_unidad = @@frm_declaracion_peso_unidad ;
$frm_declaracion_peso = @@frm_declaracion_peso ;
$frm_declaracion_estatura = @@frm_declaracion_estatura ;
$frm_declaracion_peso_unidad = @@frm_declaracion_peso_unidad ;
$frm_declaracion_peso_ganado_temp = @@frm_declaracion_peso_ganado_temp ;
$frm_declaracion_causa_ganancia_peso_temp = @@frm_declaracion_causa_ganancia_peso_temp ;
$frm_declaracion_peso_unidad = @@frm_declaracion_peso_unidad ;
$frm_declaracion_peso_perdido_temp = @@frm_declaracion_peso_perdido_temp ;
$frm_declaracion_causa_perdida_peso_temp = @@frm_declaracion_causa_perdida_peso_temp ;
$frm_declaracion_a_diabetes_label = @@frm_declaracion_a_diabetes_label ;
$frm_declaracion_a_corazon_label = @@frm_declaracion_a_corazon_label ;
$frm_declaracion_a_cancer_label = @@frm_declaracion_a_cancer_label ;
$frm_declaracion_a_cirrosis_label = @@frm_declaracion_a_cirrosis_label ;
$frm_declaracion_a_renal_label = @@frm_declaracion_a_renal_label ;
$frm_declaracion_a_pulmonar_label = @@frm_declaracion_a_pulmonar_label ;
$frm_declaracion_a_nervioso_label = @@frm_declaracion_a_nervioso_label ;
$frm_declaracion_a_tiroides_label = @@frm_declaracion_a_tiroides_label ;
$frm_declaracion_a_sida_label = @@frm_declaracion_a_sida_label ;
$frm_declaracion_a_discapacidad_label = @@frm_declaracion_a_discapacidad_label ;
$frm_declaracion_b_combo_label = @@frm_declaracion_b_combo_label ;
$frm_declaracion_b_detalle = @@frm_declaracion_b_detalle ;
$frm_declaracion_b_detalle_label = @@frm_declaracion_b_detalle_label ;
$frm_declaracion_c_combo_label = @@frm_declaracion_c_combo_label ;
$frm_declaracion_c_detalle = @@frm_declaracion_c_detalle ;
$frm_declaracion_c_detalle_label = @@frm_declaracion_c_detalle_label ;
$frm_declaracion_d_combo_label = @@frm_declaracion_d_combo_label ;
$frm_declaracion_d_motivo = @@frm_declaracion_d_motivo ;
$frm_declaracion_d_motivo_label = @@frm_declaracion_d_motivo_label ;
$frm_declaracion_d_causa = @@frm_declaracion_d_causa ;
$frm_declaracion_d_causa_label = @@frm_declaracion_d_causa_label ;
$frm_declaracion_d_resultado = @@frm_declaracion_d_resultado ;
$frm_declaracion_d_resultado_label = @@frm_declaracion_d_resultado_label ;
$frm_declaracion_e_combo_label = @@frm_declaracion_e_combo_label ;
$frm_declaracion_e_detalle = @@frm_declaracion_e_detalle ;
$frm_declaracion_e_detalle_label = @@frm_declaracion_e_detalle_label ;
$frm_declaracion_f_combo_label = @@frm_declaracion_f_combo_label ;
$frm_declaracion_f_detalle = @@frm_declaracion_f_detalle ;
$frm_declaracion_f_detalle_label = @@frm_declaracion_f_detalle_label ;
$frm_declaracion_g_combo_label = @@frm_declaracion_g_combo_label ;
$frm_declaracion_g_detalle = @@frm_declaracion_g_detalle ;
$frm_declaracion_g_detalle_label = @@frm_declaracion_g_detalle_label ;
$frm_declaracion_h_combo_label = @@frm_declaracion_h_combo_label ;
$frm_declaracion_h_edad = @@frm_declaracion_h_edad ;
$frm_declaracion_h_edad_label = @@frm_declaracion_h_edad_label ;
$frm_declaracion_h_cantidad = @@frm_declaracion_h_cantidad ;
$frm_declaracion_h_cantidad_label = @@frm_declaracion_h_cantidad_label ;
$frm_declaracion_i_detalle = @@frm_declaracion_i_detalle ;
$frm_declaracion_i_detalle_label = @@frm_declaracion_i_detalle_label ;
$frm_declaracion_j_combo_label = @@frm_declaracion_j_combo_label ;
$frm_declaracion_k_combo_label = @@frm_declaracion_k_combo_label ;
$frm_declaracion_k_frecuencia = @@frm_declaracion_k_frecuencia ;
$frm_declaracion_k_frecuencia_label = @@frm_declaracion_k_frecuencia_label ;
$frm_declaracion_k_clase = @@frm_declaracion_k_clase ;
$frm_declaracion_k_clase_label = @@frm_declaracion_k_clase_label ;
$frm_declaracion_k_cantidad = @@frm_declaracion_k_cantidad ;
$frm_declaracion_k_cantidad_label = @@frm_declaracion_k_cantidad_label ;
$frm_declaracion_l_combo_label = @@frm_declaracion_l_combo_label ;
$frm_declaracion_l_detalle = @@frm_declaracion_l_detalle ;
$frm_declaracion_l_detalle_label = @@frm_declaracion_l_detalle_label ;
$frm_declaracion_m_combo_label = @@frm_declaracion_m_combo_label ;
$frm_declaracion_m_detalle = @@frm_declaracion_m_detalle ;
$frm_declaracion_m_detalle_label = @@frm_declaracion_m_detalle_label ;
$frm_declaracion_n_combo_label = @@frm_declaracion_n_combo_label ;
$frm_declaracion_n_detalle = @@frm_declaracion_n_detalle ;
$frm_declaracion_n_detalle_label = @@frm_declaracion_n_detalle_label ;
$frm_declaracion_o_combo_label = @@frm_declaracion_o_combo_label ;
$frm_declaracion_o_detalle = @@frm_declaracion_o_detalle ;
$frm_declaracion_embarazo_label = @@frm_declaracion_embarazo_label ;
$frm_declaracion_fecha_cita = @@frm_declaracion_fecha_cita ;
$frm_declaracion_resultado_cita = @@frm_declaracion_resultado_cita ;
$frm_declaracion_resultado_cita_label = @@frm_declaracion_resultado_cita_label ;
$frm_nombre_medico = @@frm_nombre_medico ;
$frm_especialidad_medico = @@frm_especialidad_medico ;
$frm_fecha_onsulta = @@frm_fecha_onsulta ;
$frm_causa_consulta = @@frm_causa_consulta ;
$frm_parentesco_label = @@frm_parentesco_label ;
$frm_edad_actual_label = @@frm_edad_actual_label ;
$frm_enfermedades_label = @@frm_enfermedades_label ;
$frm_edad_diagnostico_label = @@frm_edad_diagnostico_label ;
$frm_parentesco_label = @@frm_parentesco_label ;
$frm_edad_morir_label = @@frm_edad_morir_label ;
$frm_causa_muerte_label = @@frm_causa_muerte_label ;
$frm_diagnostico_label = @@frm_diagnostico_label ;
$frm_aclaraciones_observacion = @@frm_aclaraciones_observacion ;
$frm_vitality_tipo_cuenta_label_temp = @@frm_vitality_tipo_cuenta_label_temp ;
$frm_vitality_banco_label_temp = @@frm_vitality_banco_label_temp ;
$frm_vitality_banco_label = @@frm_vitality_banco_label ;
$frm_vitality_numero_cuenta = @@frm_vitality_numero_cuenta ;
$frm_vitality_identificacion = @@frm_vitality_identificacion ;
$frm_vitality_titular = @@frm_vitality_titular ;
$frm_vitality_titular_apellidos = @@frm_vitality_titular_apellidos ;
$frm_monto_deposito_provisional = @@frm_monto_deposito_provisional ;
$frm_devolucion_tipo_cuenta_label_temp = @@frm_devolucion_tipo_cuenta_label_temp ;
$frm_devolucion_tipo_cuenta_label = @@frm_devolucion_tipo_cuenta_label ;
$frm_devolucion_banco_label_temp = @@frm_devolucion_banco_label_temp ;
$frm_devolucion_numero_cuenta = @@frm_devolucion_numero_cuenta ;
$frm_devolucion_identificacion = @@frm_devolucion_identificacion ;
$frm_devolucion_titular = @@frm_devolucion_titular ;
$frm_devolucion_titular_apellidos = @@frm_devolucion_titular_apellidos ;
$correo_preferido = @@correo_preferido ;
$tri_vendedor_ciudad_label = @@tri_vendedor_ciudad_label ;
$frm_fecha_solicitud = @@frm_fecha_solicitud ;
$frm_vendedor_nombre = @@frm_vendedor_nombre ;
$frm_vendedor_telefono = @@frm_vendedor_telefono ;
$frm_vendedor_email = @@frm_vendedor_email ;
$frm_monto_deposito_provisional = @@frm_monto_deposito_provisional ;
$frm_conyuge_apellido_paterno = @@frm_conyuge_apellido_paterno ;
$frm_conyuge_apellido_materno = @@frm_conyuge_apellido_materno ;
$frm_conyuge_primer_nombre = @@frm_conyuge_primer_nombre ;
$frm_conyuge_segundo_nombre = @@frm_conyuge_segundo_nombre ;
$frm_conyuge_tipo_identificacion_label = @@frm_conyuge_tipo_identificacion_label ;
$frm_conyuge_numero_identificacion = @@frm_conyuge_numero_identificacion ;
$frm_ciudad_nacimiento_label = @@frm_ciudad_nacimiento_label ;
$frm_fecha_nacimiento = @@frm_fecha_nacimiento ;
$frm_nacionalidad_label = @@frm_nacionalidad_label ;
$frm_sexo_label = @@frm_sexo_label ;
$frm_estado_civil_label = @@frm_estado_civil_label ;
$frm_numero_hijos = @@frm_numero_hijos ;
$frm_provincia_label = @@frm_provincia_label ;
$frm_canton_label = @@frm_canton_label ;
$frm_barrio = @@frm_barrio ;
$frm_calle_principal = @@frm_calle_principal ;
$frm_numero = @@frm_numero ;
$frm_calle_transversal = @@frm_calle_transversal ;
$frm_conjunto_edificio = @@frm_conjunto_edificio ;
$frm_departamento_casa = @@frm_departamento_casa ;
$frm_codigo_provincia = @@frm_codigo_provincia ;
$frm_convencional = @@frm_convencional ;
$frm_celular = @@frm_celular ;
$frm_hora_inicial_label = @@frm_hora_inicial_label ;
$frm_hora_final_label = @@frm_hora_final_label ;
$frm_correo_electronico_personal = @@frm_correo_electronico_personal ;
$frm_email_beneficiario = @@frm_email_beneficiario ;
$frm_telefono_beneficiario = @@frm_telefono_beneficiario ;
$frm_plan_tipo_beneficiario = @@frm_plan_tipo_beneficiario ;
$frm_email_contingente = @@frm_email_contingente ;
$frm_telefono_contingente = @@frm_telefono_contingente ;
$frm_plan_tipo_beneficiario_contingente = @@frm_plan_tipo_beneficiario_contingente ;
$frm_plan_pago_impuestos_label = @@frm_plan_pago_impuestos_label ;
$frm_trabajo_envio_correspondencia_label = @@frm_trabajo_envio_correspondencia_label ;
$frm_trabajo_contacto_preferido_label = @@frm_trabajo_contacto_preferido_label ;
$frm_trabajo_correo_preferido_label = @@frm_trabajo_correo_preferido_label ;
$frm_ocupacion_nombre_empresa = @@frm_ocupacion_nombre_empresa ;
$frm_ocupacion_cargo = @@frm_ocupacion_cargo ;
$frm_ocupacion_nombre_negocio = @@frm_ocupacion_nombre_negocio ;
$frm_concepto_pago = @@frm_concepto_pago ;

//////////////////////////////////////////////////////
// Cambiar de N/A a VACIO
//////////////////////////////////////////////////////

@@frm_apellido_paterno = NoAplicaVacio( $frm_apellido_paterno );
@@frm_apellido_materno = NoAplicaVacio( $frm_apellido_materno );
@@frm_primer_nombre = NoAplicaVacio( $frm_primer_nombre );
@@frm_segundo_nombre = NoAplicaVacio( $frm_segundo_nombre );
@@frm_tipo_identificacion_label = NoAplicaVacio( $frm_tipo_identificacion_label );
@@frm_numero_identificacion = NoAplicaVacio( $frm_numero_identificacion );
@@frm_lugar_residencia_habitual_label = NoAplicaVacio( $frm_lugar_residencia_habitual_label );
@@frm_pais_nacimiento_label = NoAplicaVacio( $frm_pais_nacimiento_label );
@@frm_ocupacion_profesion_label = NoAplicaVacio( $frm_ocupacion_profesion_label );
@@frm_ocupacion_tipo_empleo_label = NoAplicaVacio( $frm_ocupacion_tipo_empleo_label );
@@frm_ciudad_nacimiento_label = NoAplicaVacio( $frm_ciudad_nacimiento_label );
@@frm_fecha_nacimiento = NoAplicaVacio( $frm_fecha_nacimiento );
@@frm_nacionalidad_label = NoAplicaVacio( $frm_nacionalidad_label );
@@frm_sexo_label = NoAplicaVacio( $frm_sexo_label );
@@frm_estado_civil_label = NoAplicaVacio( $frm_estado_civil_label );
@@frm_numero_hijos = NoAplicaVacio( $frm_numero_hijos );
@@frm_provincia_label = NoAplicaVacio( $frm_provincia_label );
@@frm_canton_label = NoAplicaVacio( $frm_canton_label );
@@frm_barrio = NoAplicaVacio( $frm_barrio );
@@frm_calle_principal = NoAplicaVacio( $frm_calle_principal );
@@frm_numero = NoAplicaVacio( $frm_numero );
@@frm_calle_transversal = NoAplicaVacio( $frm_calle_transversal );
@@frm_conjunto_edificio = NoAplicaVacio( $frm_conjunto_edificio );
@@frm_departamento_casa = NoAplicaVacio( $frm_departamento_casa );
@@frm_codigo_provincia = NoAplicaVacio( $frm_codigo_provincia );
@@frm_convencional = NoAplicaVacio( $frm_convencional );
@@frm_celular = NoAplicaVacio( $frm_celular );
@@frm_hora_inicial_label = NoAplicaVacio( $frm_hora_inicial_label );
@@frm_hora_final_label = NoAplicaVacio( $frm_hora_final_label );
@@frm_correo_electronico_personal = NoAplicaVacio( $frm_correo_electronico_personal );
@@frm_ocupacion_mayor_ingresos_label = NoAplicaVacio( $frm_ocupacion_mayor_ingresos_label );
@@frm_ocupacion_tipo_label = NoAplicaVacio( $frm_ocupacion_tipo_label );
@@frm_ocupacion_otras_ocupaciones = NoAplicaVacio( $frm_ocupacion_otras_ocupaciones );
@@frm_trabajo_provincia_label = NoAplicaVacio( $frm_trabajo_provincia_label );
@@frm_trabajo_canton_label = NoAplicaVacio( $frm_trabajo_canton_label );
@@frm_trabajo_sector_barrio = NoAplicaVacio( $frm_trabajo_sector_barrio );
@@frm_trabajo_calle_principal = NoAplicaVacio( $frm_trabajo_calle_principal );
@@frm_trabajo_numero = NoAplicaVacio( $frm_trabajo_numero );
@@frm_trabajo_calle_transversal = NoAplicaVacio( $frm_trabajo_calle_transversal );
@@frm_trabajo_edificio = NoAplicaVacio( $frm_trabajo_edificio );
@@frm_trabajo_oficina = NoAplicaVacio( $frm_trabajo_oficina );
@@frm_trabajo_codigo_provincia = NoAplicaVacio( $frm_trabajo_codigo_provincia );
@@frm_trabajo_convencional = NoAplicaVacio( $frm_trabajo_convencional );
@@frm_trabajo_celular = NoAplicaVacio( $frm_trabajo_celular );
@@frm_trabajo_hora_inicial_label = NoAplicaVacio( $frm_trabajo_hora_inicial_label );
@@frm_trabajo_hora_final_label = NoAplicaVacio( $frm_trabajo_hora_final_label );
@@frm_trabajo_correo_trabajo_label = NoAplicaVacio( $frm_trabajo_correo_trabajo_label );
@@frm_relacion_ocupacion_habitual_label = NoAplicaVacio( $frm_relacion_ocupacion_habitual_label );
@@frm_frecuencia_viajes = NoAplicaVacio( $frm_frecuencia_viajes );
@@frm_otra_actividad_relacion_habitual = NoAplicaVacio( $frm_otra_actividad_relacion_habitual );
@@frm_actividades_trabajo_diario = NoAplicaVacio( $frm_actividades_trabajo_diario );
@@frm_deporte_practica_label = NoAplicaVacio( $frm_deporte_practica_label );
@@frm_tipo_practica_deporte_label = NoAplicaVacio( $frm_tipo_practica_deporte_label );
@@frm_conduce_moto_label = NoAplicaVacio( $frm_conduce_moto_label );
@@frm_cilindraje_moto = NoAplicaVacio( $frm_cilindraje_moto );
@@frm_tipo_uso_moto = NoAplicaVacio( $frm_tipo_uso_moto );
@@frm_tiene_accidentes_label = NoAplicaVacio( $frm_tiene_accidentes_label );
@@frm_fecha_accidentes = NoAplicaVacio( $frm_fecha_accidentes );
@@frm_gravedad_accidente = NoAplicaVacio( $frm_gravedad_accidente );
@@frm_piloto_label = NoAplicaVacio( $frm_piloto_label );
@@frm_trabajo_expuesta_politicamente_label = NoAplicaVacio( $frm_trabajo_expuesta_politicamente_label );
@@frm_expuesta_especifique_label = NoAplicaVacio( $frm_expuesta_especifique_label );
@@frm_referencia_personal_nombre = NoAplicaVacio( $frm_referencia_personal_nombre );
@@frm_referencia_personal_telefono = NoAplicaVacio( $frm_referencia_personal_telefono );
@@frm_referencia_comercial_nombre = NoAplicaVacio( $frm_referencia_comercial_nombre );
@@frm_referencia_comercial_telefono = NoAplicaVacio( $frm_referencia_comercial_telefono );
@@frm_referencia_bancaria_nombre_label = NoAplicaVacio( $frm_referencia_bancaria_nombre_label );
@@frm_referencia_bancaria_tipo_label = NoAplicaVacio( $frm_referencia_bancaria_tipo_label );
@@frm_referencia_bancaria_numero = NoAplicaVacio( $frm_referencia_bancaria_numero );
@@frm_financiera_actividad_principal = NoAplicaVacio( $frm_financiera_actividad_principal );
@@frm_financiera_otros_ingresos_temp = NoAplicaVacio( $frm_financiera_otros_ingresos_temp );
@@frm_ingresos_familiares = NoAplicaVacio( $frm_ingresos_familiares );
@@frm_origen_otros_ingresos_temp = NoAplicaVacio( $frm_origen_otros_ingresos_temp );
@@frm_financiera_total_ingresos = NoAplicaVacio( $frm_financiera_total_ingresos );
@@frm_financiera_total_egresos = NoAplicaVacio( $frm_financiera_total_egresos );
@@frm_financiera_total_activos = NoAplicaVacio( $frm_financiera_total_activos );
@@frm_financiera_total_pasivos = NoAplicaVacio( $frm_financiera_total_pasivos );
@@frm_ingresos_ultimo_anio = NoAplicaVacio( $frm_ingresos_ultimo_anio );
@@frm_ingresos_anterior_anio = NoAplicaVacio( $frm_ingresos_anterior_anio );
@@frm_motivo_seguro_label = NoAplicaVacio( $frm_motivo_seguro_label );
@@frm_nombre_hijos = NoAplicaVacio( $frm_nombre_hijos );
@@frm_tipo_seguro_contratado_label = NoAplicaVacio( $frm_tipo_seguro_contratado_label );
@@frm_incluye_dental_label = NoAplicaVacio( $frm_incluye_dental_label );
@@frm_valor_asegurado = NoAplicaVacio( $frm_valor_asegurado );
@@frm_prima_total = NoAplicaVacio( $frm_prima_total );
@@frm_frecuencia_pago = NoAplicaVacio( $frm_frecuencia_pago );
@@frm_plan_numero_identificacion_beneficiario = NoAplicaVacio( $frm_plan_numero_identificacion_beneficiario );
@@frm_polizaanombrede = NoAplicaVacio( $frm_polizaanombrede );
@@frm_plan_primer_nombre_label = NoAplicaVacio( $frm_plan_primer_nombre_label );
@@frm_plan_segundo_nombre_label = NoAplicaVacio( $frm_plan_segundo_nombre_label );
@@frm_plan_primer_apellido_label = NoAplicaVacio( $frm_plan_primer_apellido_label );
@@frm_plan_segundo_apellido_label = NoAplicaVacio( $frm_plan_segundo_apellido_label );
@@frm_plan_prentesco_label = NoAplicaVacio( $frm_plan_prentesco_label );
@@frm_plan_porcentaje_label = NoAplicaVacio( $frm_plan_porcentaje_label );
@@frm_plan_numero_identificacion_beneficiario_contingente = NoAplicaVacio( $frm_plan_numero_identificacion_beneficiario_contingente );
@@frm_plan_primer_nombre_contingente = NoAplicaVacio( $frm_plan_primer_nombre_contingente );
@@frm_plan_segundo_nombre_contingente = NoAplicaVacio( $frm_plan_segundo_nombre_contingente );
@@frm_plan_primer_apellido_contingente = NoAplicaVacio( $frm_plan_primer_apellido_contingente );
@@frm_plan_segundo_apellido_contingente = NoAplicaVacio( $frm_plan_segundo_apellido_contingente );
@@frm_plan_prentesco_contingente_label = NoAplicaVacio( $frm_plan_prentesco_contingente_label );
@@frm_plan_porcentaje_contingente = NoAplicaVacio( $frm_plan_porcentaje_contingente );
@@frm_dental_identificacion = NoAplicaVacio( $frm_dental_identificacion );
@@frm_dental_primer_nombre = NoAplicaVacio( $frm_dental_primer_nombre );
@@frm_dental_segundo_nombre = NoAplicaVacio( $frm_dental_segundo_nombre );
@@frm_dental_primer_apellido = NoAplicaVacio( $frm_dental_primer_apellido );
@@frm_dental_segundo_apellido = NoAplicaVacio( $frm_dental_segundo_apellido );
@@frm_dental_parentesco_label = NoAplicaVacio( $frm_dental_parentesco_label );
@@frm_dental_fecha_nacimiento = NoAplicaVacio( $frm_dental_fecha_nacimiento );
@@frm_plan_relacion_label = NoAplicaVacio( $frm_plan_relacion_label );
@@frm_plan_tipo_relacion_label = NoAplicaVacio( $frm_plan_tipo_relacion_label );
@@frm_plan_otra_label = NoAplicaVacio( $frm_plan_otra_label );
@@frm_opcion_liquidacion_valor_label = NoAplicaVacio( $frm_opcion_liquidacion_valor_label );
@@frm_plazo_cuotas_liquidacion_temp = NoAplicaVacio( $frm_plazo_cuotas_liquidacion_temp );
@@frm_pago_unico_porcentaje_temp = NoAplicaVacio( $frm_pago_unico_porcentaje_temp );
@@frm_pago_cuota_porcentaje_temp = NoAplicaVacio( $frm_pago_cuota_porcentaje_temp );
@@frm_plazo_cuotas_liquidacion_combinada_temp = NoAplicaVacio( $frm_plazo_cuotas_liquidacion_combinada_temp );
@@frm_ramooplan_label = NoAplicaVacio( $frm_ramooplan_label );
@@frm_compania = NoAplicaVacio( $frm_compania );
@@frm_valor_asegurado_otros = NoAplicaVacio( $frm_valor_asegurado_otros );
@@frm_solicitud_seguro_vegente_label = NoAplicaVacio( $frm_solicitud_seguro_vegente_label );
@@frm_solicitud_extraprima_label = NoAplicaVacio( $frm_solicitud_extraprima_label );
@@frm_seguro_negado_label = NoAplicaVacio( $frm_seguro_negado_label );
@@frm_seguro_exequial =  ( @@frm_seguro_exequial_label == 'SI' ? 'S' : 'N');
@@frm_causa_negacion_temp = NoAplicaVacio( $frm_causa_negacion_temp );
@@frm_declaracion_peso_unidad = NoAplicaVacio( $frm_declaracion_peso_unidad );
@@frm_declaracion_peso = NoAplicaVacio( $frm_declaracion_peso );
@@frm_declaracion_estatura = NoAplicaVacio( $frm_declaracion_estatura );
@@frm_declaracion_peso_unidad = NoAplicaVacio( $frm_declaracion_peso_unidad );
@@frm_declaracion_peso_ganado_temp = NoAplicaVacio( $frm_declaracion_peso_ganado_temp );
@@frm_declaracion_causa_ganancia_peso_temp = NoAplicaVacio( $frm_declaracion_causa_ganancia_peso_temp );
@@frm_declaracion_peso_unidad = NoAplicaVacio( $frm_declaracion_peso_unidad );
@@frm_declaracion_peso_perdido_temp = NoAplicaVacio( $frm_declaracion_peso_perdido_temp );
@@frm_declaracion_causa_perdida_peso_temp = NoAplicaVacio( $frm_declaracion_causa_perdida_peso_temp );
@@frm_declaracion_a_diabetes_label = NoAplicaVacio( $frm_declaracion_a_diabetes_label );
@@frm_declaracion_a_corazon_label = NoAplicaVacio( $frm_declaracion_a_corazon_label );
@@frm_declaracion_a_cancer_label = NoAplicaVacio( $frm_declaracion_a_cancer_label );
@@frm_declaracion_a_cirrosis_label = NoAplicaVacio( $frm_declaracion_a_cirrosis_label );
@@frm_declaracion_a_renal_label = NoAplicaVacio( $frm_declaracion_a_renal_label );
@@frm_declaracion_a_pulmonar_label = NoAplicaVacio( $frm_declaracion_a_pulmonar_label );
@@frm_declaracion_a_nervioso_label = NoAplicaVacio( $frm_declaracion_a_nervioso_label );
@@frm_declaracion_a_tiroides_label = NoAplicaVacio( $frm_declaracion_a_tiroides_label );
@@frm_declaracion_a_sida_label = NoAplicaVacio( $frm_declaracion_a_sida_label );
@@frm_declaracion_a_discapacidad_label = NoAplicaVacio( $frm_declaracion_a_discapacidad_label );
@@frm_declaracion_b_combo_label = NoAplicaVacio( $frm_declaracion_b_combo_label );
@@frm_declaracion_b_detalle = NoAplicaVacio( $frm_declaracion_b_detalle );
@@frm_declaracion_b_detalle_label = NoAplicaVacio( $frm_declaracion_b_detalle_label );
@@frm_declaracion_c_combo_label = NoAplicaVacio( $frm_declaracion_c_combo_label );
@@frm_declaracion_c_detalle = NoAplicaVacio( $frm_declaracion_c_detalle );
@@frm_declaracion_c_detalle_label = NoAplicaVacio( $frm_declaracion_c_detalle_label );
@@frm_declaracion_d_combo_label = NoAplicaVacio( $frm_declaracion_d_combo_label );
@@frm_declaracion_d_motivo = NoAplicaVacio( $frm_declaracion_d_motivo );
@@frm_declaracion_d_motivo_label = NoAplicaVacio( $frm_declaracion_d_motivo_label );
@@frm_declaracion_d_causa = NoAplicaVacio( $frm_declaracion_d_causa );
@@frm_declaracion_d_causa_label = NoAplicaVacio( $frm_declaracion_d_causa_label );
@@frm_declaracion_d_resultado = NoAplicaVacio( $frm_declaracion_d_resultado );
@@frm_declaracion_d_resultado_label = NoAplicaVacio( $frm_declaracion_d_resultado_label );
@@frm_declaracion_e_combo_label = NoAplicaVacio( $frm_declaracion_e_combo_label );
@@frm_declaracion_e_detalle = NoAplicaVacio( $frm_declaracion_e_detalle );
@@frm_declaracion_e_detalle_label = NoAplicaVacio( $frm_declaracion_e_detalle_label );
@@frm_declaracion_f_combo_label = NoAplicaVacio( $frm_declaracion_f_combo_label );
@@frm_declaracion_f_detalle = NoAplicaVacio( $frm_declaracion_f_detalle );
@@frm_declaracion_f_detalle_label = NoAplicaVacio( $frm_declaracion_f_detalle_label );
@@frm_declaracion_g_combo_label = NoAplicaVacio( $frm_declaracion_g_combo_label );
@@frm_declaracion_g_detalle = NoAplicaVacio( $frm_declaracion_g_detalle );
@@frm_declaracion_g_detalle_label = NoAplicaVacio( $frm_declaracion_g_detalle_label );
@@frm_declaracion_h_combo_label = NoAplicaVacio( $frm_declaracion_h_combo_label );
@@frm_declaracion_h_edad = NoAplicaVacio( $frm_declaracion_h_edad );
@@frm_declaracion_h_edad_label = NoAplicaVacio( $frm_declaracion_h_edad_label );
@@frm_declaracion_h_cantidad = NoAplicaVacio( $frm_declaracion_h_cantidad );
@@frm_declaracion_h_cantidad_label = NoAplicaVacio( $frm_declaracion_h_cantidad_label );
@@frm_declaracion_i_detalle = NoAplicaVacio( $frm_declaracion_i_detalle );
@@frm_declaracion_i_detalle_label = NoAplicaVacio( $frm_declaracion_i_detalle_label );
@@frm_declaracion_j_combo_label = NoAplicaVacio( $frm_declaracion_j_combo_label );
@@frm_declaracion_k_combo_label = NoAplicaVacio( $frm_declaracion_k_combo_label );
@@frm_declaracion_k_frecuencia = NoAplicaVacio( $frm_declaracion_k_frecuencia );
@@frm_declaracion_k_frecuencia_label = NoAplicaVacio( $frm_declaracion_k_frecuencia_label );
@@frm_declaracion_k_clase = NoAplicaVacio( $frm_declaracion_k_clase );
@@frm_declaracion_k_clase_label = NoAplicaVacio( $frm_declaracion_k_clase_label );
@@frm_declaracion_k_cantidad = NoAplicaVacio( $frm_declaracion_k_cantidad );
@@frm_declaracion_k_cantidad_label = NoAplicaVacio( $frm_declaracion_k_cantidad_label );
@@frm_declaracion_l_combo_label = NoAplicaVacio( $frm_declaracion_l_combo_label );
@@frm_declaracion_l_detalle = NoAplicaVacio( $frm_declaracion_l_detalle );
@@frm_declaracion_l_detalle_label = NoAplicaVacio( $frm_declaracion_l_detalle_label );
@@frm_declaracion_m_combo_label = NoAplicaVacio( $frm_declaracion_m_combo_label );
@@frm_declaracion_m_detalle = NoAplicaVacio( $frm_declaracion_m_detalle );
@@frm_declaracion_m_detalle_label = NoAplicaVacio( $frm_declaracion_m_detalle_label );
@@frm_declaracion_n_combo_label = NoAplicaVacio( $frm_declaracion_n_combo_label );
@@frm_declaracion_n_detalle = NoAplicaVacio( $frm_declaracion_n_detalle );
@@frm_declaracion_n_detalle_label = NoAplicaVacio( $frm_declaracion_n_detalle_label );
@@frm_declaracion_o_combo_label = NoAplicaVacio( $frm_declaracion_o_combo_label );
@@frm_declaracion_o_detalle = NoAplicaVacio( $frm_declaracion_o_detalle );
@@frm_declaracion_embarazo_label = NoAplicaVacio( $frm_declaracion_embarazo_label );
@@frm_declaracion_fecha_cita = NoAplicaVacio( $frm_declaracion_fecha_cita );
@@frm_declaracion_resultado_cita = NoAplicaVacio( $frm_declaracion_resultado_cita );
@@frm_declaracion_resultado_cita_label = NoAplicaVacio( $frm_declaracion_resultado_cita_label );
@@frm_nombre_medico = NoAplicaVacio( $frm_nombre_medico );
@@frm_especialidad_medico = NoAplicaVacio( $frm_especialidad_medico );
@@frm_fecha_onsulta = NoAplicaVacio( $frm_fecha_onsulta );
@@frm_causa_consulta = NoAplicaVacio( $frm_causa_consulta );
@@frm_parentesco_label = NoAplicaVacio( $frm_parentesco_label );
@@frm_edad_actual_label = NoAplicaVacio( $frm_edad_actual_label );
@@frm_enfermedades_label = NoAplicaVacio( $frm_enfermedades_label );
@@frm_edad_diagnostico_label = NoAplicaVacio( $frm_edad_diagnostico_label );
@@frm_parentesco_label = NoAplicaVacio( $frm_parentesco_label );
@@frm_edad_morir_label = NoAplicaVacio( $frm_edad_morir_label );
@@frm_causa_muerte_label = NoAplicaVacio( $frm_causa_muerte_label );
@@frm_diagnostico_label = NoAplicaVacio( $frm_diagnostico_label );
@@frm_aclaraciones_observacion = NoAplicaVacio( $frm_aclaraciones_observacion );
@@frm_vitality_tipo_cuenta_label_temp = NoAplicaVacio( $frm_vitality_tipo_cuenta_label_temp );
@@frm_vitality_banco_label_temp = NoAplicaVacio( $frm_vitality_banco_label_temp );
@@frm_vitality_banco_label = NoAplicaVacio( $frm_vitality_banco_label );
@@frm_vitality_numero_cuenta = NoAplicaVacio( $frm_vitality_numero_cuenta );
@@frm_vitality_identificacion = NoAplicaVacio( $frm_vitality_identificacion );
@@frm_vitality_titular = NoAplicaVacio( $frm_vitality_titular );
@@frm_vitality_titular_apellidos = NoAplicaVacio( $frm_vitality_titular_apellidos );
@@frm_monto_deposito_provisional = NoAplicaVacio( $frm_monto_deposito_provisional );
@@frm_devolucion_tipo_cuenta_label_temp = NoAplicaVacio( $frm_devolucion_tipo_cuenta_label_temp );
@@frm_devolucion_tipo_cuenta_label = NoAplicaVacio( $frm_devolucion_tipo_cuenta_label );
@@frm_devolucion_banco_label_temp = NoAplicaVacio( $frm_devolucion_banco_label_temp );
@@frm_devolucion_numero_cuenta = NoAplicaVacio( $frm_devolucion_numero_cuenta );
@@frm_devolucion_identificacion = NoAplicaVacio( $frm_devolucion_identificacion );
@@frm_devolucion_titular = NoAplicaVacio( $frm_devolucion_titular );
@@frm_devolucion_titular_apellidos = NoAplicaVacio( $frm_devolucion_titular_apellidos );
@@correo_preferido = NoAplicaVacio( $correo_preferido );
@@tri_vendedor_ciudad_label = NoAplicaVacio( $tri_vendedor_ciudad_label );
@@frm_fecha_solicitud = NoAplicaVacio( $frm_fecha_solicitud );
@@frm_vendedor_nombre = NoAplicaVacio( $frm_vendedor_nombre );
@@frm_vendedor_telefono = NoAplicaVacio( $frm_vendedor_telefono );
@@frm_vendedor_email = NoAplicaVacio( $frm_vendedor_email );
@@frm_monto_deposito_provisional = NoAplicaVacio( $frm_monto_deposito_provisional );
@@frm_conyuge_apellido_paterno = NoAplicaVacio( $frm_conyuge_apellido_paterno );
@@frm_conyuge_apellido_materno = NoAplicaVacio( $frm_conyuge_apellido_materno );
@@frm_conyuge_primer_nombre = NoAplicaVacio( $frm_conyuge_primer_nombre );
@@frm_conyuge_segundo_nombre = NoAplicaVacio( $frm_conyuge_segundo_nombre );
@@frm_conyuge_tipo_identificacion_label = NoAplicaVacio( $frm_conyuge_tipo_identificacion_label );
@@frm_conyuge_numero_identificacion = NoAplicaVacio( $frm_conyuge_numero_identificacion );
@@frm_ciudad_nacimiento_label = NoAplicaVacio( $frm_ciudad_nacimiento_label );
@@frm_fecha_nacimiento = NoAplicaVacio( $frm_fecha_nacimiento );
@@frm_nacionalidad_label = NoAplicaVacio( $frm_nacionalidad_label );
@@frm_sexo_label = NoAplicaVacio( $frm_sexo_label );
@@frm_estado_civil_label = NoAplicaVacio( $frm_estado_civil_label );
@@frm_numero_hijos = NoAplicaVacio( $frm_numero_hijos );
@@frm_provincia_label = NoAplicaVacio( $frm_provincia_label );
@@frm_canton_label = NoAplicaVacio( $frm_canton_label );
@@frm_barrio = NoAplicaVacio( $frm_barrio );
@@frm_calle_principal = NoAplicaVacio( $frm_calle_principal );
@@frm_numero = NoAplicaVacio( $frm_numero );
@@frm_calle_transversal = NoAplicaVacio( $frm_calle_transversal );
@@frm_conjunto_edificio = NoAplicaVacio( $frm_conjunto_edificio );
@@frm_departamento_casa = NoAplicaVacio( $frm_departamento_casa );
@@frm_codigo_provincia = NoAplicaVacio( $frm_codigo_provincia );
@@frm_convencional = NoAplicaVacio( $frm_convencional );
@@frm_celular = NoAplicaVacio( $frm_celular );
@@frm_hora_inicial_label = NoAplicaVacio( $frm_hora_inicial_label );
@@frm_hora_final_label = NoAplicaVacio( $frm_hora_final_label );
@@frm_correo_electronico_personal = NoAplicaVacio( $frm_correo_electronico_personal );
@@frm_email_beneficiario = NoAplicaVacio( $frm_email_beneficiario );
@@frm_telefono_beneficiario = NoAplicaVacio( $frm_telefono_beneficiario );
@@frm_plan_tipo_beneficiario = NoAplicaVacio( $frm_plan_tipo_beneficiario );
@@frm_email_contingente = NoAplicaVacio( $frm_email_contingente );
@@frm_telefono_contingente = NoAplicaVacio( $frm_telefono_contingente );
@@frm_plan_tipo_beneficiario_contingente = NoAplicaVacio( $frm_plan_tipo_beneficiario_contingente );
@@frm_plan_pago_impuestos_label = NoAplicaVacio( $frm_plan_pago_impuestos_label );
@@frm_trabajo_envio_correspondencia_label = NoAplicaVacio( $frm_trabajo_envio_correspondencia_label );
@@frm_trabajo_contacto_preferido_label = NoAplicaVacio( $frm_trabajo_contacto_preferido_label );
@@frm_trabajo_correo_preferido_label = NoAplicaVacio( $frm_trabajo_correo_preferido_label );
@@frm_ocupacion_nombre_empresa = NoAplicaVacio( $frm_ocupacion_nombre_empresa );
@@frm_ocupacion_cargo = NoAplicaVacio( $frm_ocupacion_cargo );
@@frm_ocupacion_nombre_negocio = NoAplicaVacio( $frm_ocupacion_nombre_negocio );
@@frm_concepto_pago = NoAplicaVacio( $frm_concepto_pago );



$tot = count(@=grd_vinculos);
for ($i = 1; $i <= $tot; $i++) {
	$frm_plan_otra = @@grd_vinculos[$i]['frm_plan_otra'];
	@@grd_vinculos[$i]['frm_plan_otra'] = NoAplicaVacio($frm_plan_otra);

	// @@grd_vinculos[$i]['frm_plan_otra'] = NoAplicaVacio(@#grd_vinculos[$i]['frm_plan_otra']);
	// @@grd_vinculos[$i]['frm_plan_otra_label'] = NoAplicaVacio(@#grd_vinculos[$i]['frm_plan_otra_label']);
}


$tot = count(@=grd_beneficiario);
@@tmp_total = $tot;

if ($tot > 0) {
for ($i = 1; $i <= $tot; $i++) {
	$beneficiario = @@grd_beneficiario[$i]['frm_plan_numero_identificacion_beneficiario'];
	$beneficiario_label = @@grd_beneficiario[$i]['frm_plan_numero_identificacion_beneficiario_label'];

	@@grd_beneficiario[$i]['frm_plan_numero_identificacion_beneficiario'] = NoAplicaVacio( $beneficiario );
	@@grd_beneficiario[$i]['frm_plan_numero_identificacion_beneficiario_label'] = NoAplicaVacio( $beneficiario_label );
}}

if (is_array(@=grd_beneficiario) && isset(@=grd_beneficiario[1])) {
	@@frm_plan_primer_nombre_label = NoAplicaVacio(isset(@=grd_beneficiario[1]['frm_plan_primer_nombre_label']) ? @=grd_beneficiario[1]['frm_plan_primer_nombre_label'] : '');
	@@frm_plan_segundo_nombre_label = NoAplicaVacio(isset(@=grd_beneficiario[1]['frm_plan_segundo_nombre_label']) ? @=grd_beneficiario[1]['frm_plan_segundo_nombre_label'] : '');
	@@frm_plan_primer_apellido_label = NoAplicaVacio(isset(@=grd_beneficiario[1]['frm_plan_primer_apellido_label']) ? @=grd_beneficiario[1]['frm_plan_primer_apellido_label'] : '');
	@@frm_plan_segundo_apellido_label = NoAplicaVacio(isset(@=grd_beneficiario[1]['frm_plan_segundo_apellido_label']) ? @=grd_beneficiario[1]['frm_plan_segundo_apellido_label'] : '');
	@@frm_plan_numero_identificacion_beneficiario = NoAplicaVacio(isset(@=grd_beneficiario[1]['frm_plan_numero_identificacion_beneficiario']) ? @=grd_beneficiario[1]['frm_plan_numero_identificacion_beneficiario'] : '');
	@@frm_plan_prentesco_label = NoAplicaVacio(isset(@=grd_beneficiario[1]['frm_plan_prentesco_label']) ? @=grd_beneficiario[1]['frm_plan_prentesco_label'] : '');
	@@frm_plan_porcentaje_label = NoAplicaVacio(isset(@=grd_beneficiario[1]['frm_plan_porcentaje_label']) ? @=grd_beneficiario[1]['frm_plan_porcentaje_label'] : '');
}

if(is_array(@=grid_beneficiarios_contingentes)){
	$tot = count(@=grid_beneficiarios_contingentes);
	if(@=grid_beneficiarios_contingentes[1]['frm_plan_numero_identificacion_beneficiario_contingente'] == ""){
		@@grid_beneficiarios_contingentes = "";
	}else{
		for ($i = 1; $i <= $tot; $i++) {

			$beneficiario_contingente = @@grid_beneficiarios_contingentes[$i]['frm_plan_numero_identificacion_beneficiario_contingente'];
			$beneficiario_contingente_label = @@grid_beneficiarios_contingentes[$i]['frm_plan_numero_identificacion_beneficiario_contingente_label'];

			@@grid_beneficiarios_contingentes[$i]['frm_plan_numero_identificacion_beneficiario_contingente'] = NoAplicaVacio( $beneficiario_contingente );
			@@grid_beneficiarios_contingentes[$i]['frm_plan_numero_identificacion_beneficiario_contingente_label'] = NoAplicaVacio( $beneficiario_contingente_label );
		}
	}
}

////////////////
//Grillas vacias
////////////////
if(is_array(@=grid_medicos_consultados)){
	if(@=grid_medicos_consultados[1]['frm_nombre_medico'] == "N/A"){
		@@grid_medicos_consultados = "";
	}

	if(@=grid_otros_seguros[1]['frm_ramooplan_label'] == "N/A"){
		@@grid_otros_seguros = "";
	}

	if(@=grid_dental[1]['frm_tipo_identificacion_dental'] == ""){
		@@grid_dental = "";
	}

	if(@=grid_seguro_exequial[1]['frm_exequial_identificacion'] == "N/A"){
		@@grid_seguro_exequial = "";
	}

	if(@=grd_beneficiario[1]['frm_plan_primer_nombre'] == ""){
		@@grd_beneficiario = "";
	}

	if(@=grid_beneficiarios_contingentes[1]['frm_plan_primer_nombre_contingente'] == "N/A"){
		@@grid_beneficiarios_contingentes = "";
	}
}

@@tmp_ejecuto  = @@APP_NUMBER + 1;
