<?php
/*******************************************************
 *
 * Generated by ProcessMaker Trigger Wizard
 * Library: ProcessMaker Functions
 * Method: PMF Send Message
 * Date: 2020-08-30 10:35:06
 *
 * ProcessMaker 2020
 *
 *******************************************************/
$app_number = @@APP_NUMBER;
$tipo_req = @@frm_datosSolicitud_tipo_label;
$user = @@USER_LOGGED;
$sql = "SELECT USR_EMAIL MAIL FROM USERS WHERE USR_UID  = '$user'";
$resultadoCorreos = executeQuery($sql);
$responsable_emision_mail = $resultadoCorreos[1]['MAIL'];
$cc = $resultadoCorreos[1]['CAMPO2'];

if (@@frm_responsable_emision_mail == '') {
    @@frm_responsable_emision_mail = $responsable_emision_mail;
}

//validacion por tarea
switch (@@TASK) {
    //tarea 1
    case '425464187652152567c32c0021157413':
        $de = '';
        $para = @@frm_responsable_emision_mail;

        $bcc = '';
        $asunto = "Notificación de caso en BPM $app_number";
        $texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
        $texto .= '<p align="justify">Se le notifica que se requiere la asignación del caso ' . $app_number . ' de tipo ' . $tipo_req . ' para su realización, por favor gestionarlo de acuerdo a las condiciones solicitadas</tipo></p>';
        $comentario = @@frm_comentario;
        $accion     = @@frm_accion;
        $plantilla_rec = 'Plantilla_mail.html';

        @@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' => $texto));



        break;
    //tarea 2
    case '45952911965215256264370054809440':
        $de = '';
        $para = @@frm_responsable_emision_mail;
        //$para = 'jcchachalo@gmail.com';

        $bcc = '';
        $asunto = "Notificación de caso en BPM $app_number";
        $texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
        $texto .= '<p align="justify">Se le notifica que se requiere la asignación del caso ' . $app_number . ' de tipo ' . $tipo_req . ' para su realización, por favor gestionarlo de acuerdo a las condiciones solicitadas</tipo></p>';
        $comentario = @@frm_comentario;
        $accion     = @@frm_accion;
        $plantilla_rec = 'Plantilla_mail.html';

        @@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' => $texto));

        break;
    //tarea 2
    case '56790794265215256872664077973746':
        $de = '';
        $para = @@frm_responsable_emision_mail;


        $bcc = '';
        $asunto = "Notificación de caso en BPM $app_number";
        $texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
        $texto .= '<p align="justify">Se le notifica que se requiere la asignación del caso ' . $app_number . ' de tipo ' . $tipo_req . ' para su realización, por favor gestionarlo de acuerdo a las condiciones solicitadas</tipo></p>';
        $comentario = @@frm_comentario;
        $accion     = @@frm_accion;
        $plantilla_rec = 'Plantilla_mail.html';

        @@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' => $texto));

        break;
    //tarea 3
    case '35160580265215256541ab8094100787':
        $de = '';
        $para = @@frm_responsable_emision_mail;
        //$para = 'jcchachalo@gmail.com';

        $bcc = '';
        $asunto = "Notificación de caso en BPM $app_number";
        $texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
        $texto .= '<p align="justify">Se le notifica que se requiere la asignación del caso ' . $app_number . ' de tipo ' . $tipo_req . ' para su realización, por favor gestionarlo de acuerdo a las condiciones solicitadas</tipo></p>';
        $comentario = @@frm_comentario;
        $accion     = @@frm_accion;
        $plantilla_rec = 'Plantilla_mail.html';

        @@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' => $texto));

        break;
    //tarea 4
    case '272989440652152565f2779059595363':
        $de = '';
        $para = @@frm_responsable_emision_mail;
        //$para = 'jcchachalo@gmail.com';

        $bcc = '';
        $asunto = "Notificación de caso en BPM $app_number";
        $texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
        $texto .= '<p align="justify">Se le notifica que se requiere la asignación del caso ' . $app_number . ' de tipo ' . $tipo_req . ' para su realización, por favor gestionarlo de acuerdo a las condiciones solicitadas</tipo></p>';
        $comentario = @@frm_comentario;
        $accion     = @@frm_accion;
        $plantilla_rec = 'Plantilla_mail.html';

        @@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' => $texto));
        break;
    //tarea 5
    case '86468730265215256b284b6071813170':
        $de = '';
        $para = @@frm_responsable_emision_mail;
        //$para = 'jcchachalo@gmail.com';

        $bcc = '';
        $asunto = "Notificación de caso en BPM $app_number";
        $texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
        $texto .= '<p align="justify">Se le notifica que se requiere la asignación del caso ' . $app_number . ' de tipo ' . $tipo_req . ' para su realización, por favor gestionarlo de acuerdo a las condiciones solicitadas</tipo></p>';
        $comentario = @@frm_comentario;
        $accion     = @@frm_accion;
        $plantilla_rec = 'Plantilla_mail.html';

        @@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' => $texto));

        break;
    case '8247927376521525676e1b9045713130':
        $de = '';
        $para = @@frm_responsable_emision_mail;
        //$para = 'jcchachalo@gmail.com';

        $bcc = '';
        $asunto = "Notificación de caso en BPM $app_number";
        $texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
        $texto .= '<p align="justify">Se le notifica que se requiere la asignación del caso ' . $app_number . ' de tipo ' . $tipo_req . ' para su realización, por favor gestionarlo de acuerdo a las condiciones solicitadas</tipo></p>';
        $comentario = @@frm_comentario;
        $accion     = @@frm_accion;
        $plantilla_rec = 'Plantilla_mail.html';

        @@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' => $texto));

        break;
    case '8961052146521525664ad68072679479':
        $de = '';
        $para = @@frm_responsable_emision_mail;
        //$para = 'jcchachalo@gmail.com';

        $bcc = '';
        $asunto = "Notificación de caso en BPM $app_number";
        $texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
        $texto .= '<p align="justify">Se le notifica que se requiere la asignación del caso ' . $app_number . ' de tipo ' . $tipo_req . ' para su realización, por favor gestionarlo de acuerdo a las condiciones solicitadas</tipo></p>';
        $comentario = @@frm_comentario;
        $accion     = @@frm_accion;
        $plantilla_rec = 'Plantilla_mail.html';

        @@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' => $texto));

        break;
    case '71065108665215256715fb0045960866':
        $de = '';
        $para = @@frm_responsable_emision_mail;
        //$para = 'jcchachalo@gmail.com';

        $bcc = '';
        $asunto = "Notificación de caso en BPM $app_number";
        $texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
        $texto .= '<p align="justify">Se le notifica que se requiere la asignación del caso ' . $app_number . ' de tipo ' . $tipo_req . ' para su realización, por favor gestionarlo de acuerdo a las condiciones solicitadas</tipo></p>';
        $comentario = @@frm_comentario;
        $accion     = @@frm_accion;
        $plantilla_rec = 'Plantilla_mail.html';

        @@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' => $texto));

        break;
    //tarea 6
    case '13941977965215256a2e7c1020727543':
        $de = '';
        $para = @@frm_responsable_emision_mail;
        //$para = 'jcchachalo@gmail.com';

        $bcc = '';
        $asunto = "Notificación de caso en BPM $app_number";
        $texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
        $texto .= '<p align="justify">Se le notifica que se requiere la asignación del caso ' . $app_number . ' de tipo ' . $tipo_req . ' para su realización, por favor gestionarlo de acuerdo a las condiciones solicitadas</tipo></p>';
        $comentario = @@frm_comentario;
        $accion     = @@frm_accion;
        $plantilla_rec = 'Plantilla_mail.html';

        @@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' => $texto));

        break;
    //tarea 7
    case '45377697965215256976d89082488170':
        $de = '';
        $para = @@frm_responsable_emision_mail;
        //$para = 'jcchachalo@gmail.com';

        $bcc = '';
        $asunto = "Notificación de caso en BPM $app_number";
        $texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
        $texto .= '<p align="justify">Se le notifica que se requiere la asignación del caso ' . $app_number . ' de tipo ' . $tipo_req . ' para su realización, por favor gestionarlo de acuerdo a las condiciones solicitadas</tipo></p>';
        $comentario = @@frm_comentario;
        $accion     = @@frm_accion;
        $plantilla_rec = 'Plantilla_mail.html';

        @@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' => $texto));

        break;
    //tarea 7
    case '3307487626521525620fea9042882681':
        $de = '';
        $para = @@frm_responsable_emision_mail;
        //$para = 'jcchachalo@gmail.com';

        $bcc = '';
        $asunto = "Notificación de caso en BPM $app_number";
        $texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
        $texto .= '<p align="justify">Se le notifica que se requiere la asignación del caso ' . $app_number . ' de tipo ' . $tipo_req . ' para su realización, por favor gestionarlo de acuerdo a las condiciones solicitadas</tipo></p>';
        $comentario = @@frm_comentario;
        $accion     = @@frm_accion;
        $plantilla_rec = 'Plantilla_mail.html';

        @@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' => $texto));

        break;
    //tarea 8
    case '926762764652152568160d9033064912':
        $de = '';
        $para = @@frm_responsable_emision_mail;
        //$para = 'jcchachalo@gmail.com';

        $bcc = '';
        $asunto = "Notificación de caso en BPM $app_number";
        $texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
        $texto .= '<p align="justify">Se le notifica que se requiere la asignación del caso ' . $app_number . ' de tipo ' . $tipo_req . ' para su realización, por favor gestionarlo de acuerdo a las condiciones solicitadas</tipo></p>';
        $comentario = @@frm_comentario;
        $accion     = @@frm_accion;
        $plantilla_rec = 'Plantilla_mail.html';

        @@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' => $texto));

        break;
    //tarea 9
    case '879775474652152561bba84010841596':
        $de = '';
        $para = @@frm_responsable_emision_mail;
        //$para = 'jcchachalo@gmail.com';

        $bcc = '';
        $asunto = "Notificación de caso en BPM $app_number";
        $texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
        $texto .= '<p align="justify">Se le notifica que se requiere la asignación del caso ' . $app_number . ' de tipo ' . $tipo_req . ' para su realización, por favor gestionarlo de acuerdo a las condiciones solicitadas</tipo></p>';
        $comentario = @@frm_comentario;
        $accion     = @@frm_accion;
        $plantilla_rec = 'Plantilla_mail.html';

        @@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' => $texto));

        break;
    //tarea 10
    case '286679760652152566b8eb9025659945':
        $de = '';
        $para = @@frm_responsable_emision_mail;
        //$para = 'jcchachalo@gmail.com';

        $bcc = '';
        $asunto = "Notificación de caso en BPM $app_number";
        $texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
        $texto .= '<p align="justify">Se le notifica que se requiere la asignación del caso ' . $app_number . ' de tipo ' . $tipo_req . ' para su realización, por favor gestionarlo de acuerdo a las condiciones solicitadas</tipo></p>';
        $comentario = @@frm_comentario;
        $accion     = @@frm_accion;
        $plantilla_rec = 'Plantilla_mail.html';

        @@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' => $texto));

        break;
    //tarea 11
    case '46270677565215256ad8482021797184':
        $de = '';
        $para = @@frm_responsable_emision_mail;
        //$para = 'jcchachalo@gmail.com';

        $bcc = '';
        $asunto = "Notificación de caso en BPM $app_number";
        $texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
        $texto .= '<p align="justify">Se le notifica que se requiere la asignación del caso ' . $app_number . ' de tipo ' . $tipo_req . ' para su realización, por favor gestionarlo de acuerdo a las condiciones solicitadas</tipo></p>';
        $comentario = @@frm_comentario;
        $accion     = @@frm_accion;
        $plantilla_rec = 'Plantilla_mail.html';

        @@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' => $texto));

        break;
}
