<?php
//<?php
/*******************************************************
*
* Generated by ProcessMaker Trigger Wizard
* Library: ProcessMaker Functions
* Method: PMF Send Message
* Date: 2020-08-30 10:35:06
*
* ProcessMaker 2020
*
*******************************************************/
$app_number = @@APP_NUMBER;
$tipo_req = @@frm_datosSolicitud_tipo_label;
//validacion por tarea
switch (@@TASK){
//tarea 2
case '8125949826537369e288364020529993':
$de = '';
$para = @@tri_user_inicial_mail;
$cc = '';
$bcc = 'hbautista@segurosequinoccial.com';
$accion = @@frm_accion;
$comentario = @@frm_comentario;
	if($accion == 'REGULARIZAR'){
		$causas = '';
		foreach(@=chk_motivos as $datamot){
			$causas .= $datamot.' - ';
		}
		
		$causa_label = @@chk_motivos_label;
		
		$asunto = "Reproceso de caso en BPM ". @#APP_NUMBER;
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Una vez analizado en caso en referencia, se requieren las siguientes regularizaciones:</p>';
		$texto .= '<p align="justify">'.$comentario.'</p>';
		$texto .= '<p align="justify">Causas del reproceso:</p>';
		$texto .= '<p align="justify">'.$causa_label.'</p>';
			
	}	
	if($accion == 'FINALIZAR'){
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Una vez analizado en caso en referencia, adjuntamos la decisión del mismo:</p>';
	$texto .= '<p align="justify">'.$comentario.'</p>';
		@@tri_texto_mail = $texto;
	}

$plantilla_rec = 'Plantilla_mail.html';

@@envio_mail_t1 = PMFSendMessage(@@APPLICATION,$de,$para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
$texto));

break;
//tarea 3
case '349144081653736ee2c8c93089870016':
$de = '';
$para = @@tri_user_inicial_mail;
$cc = @@tri_user_suscriptor_mail;
$bcc = 'hbautista@segurosequinoccial.com';
$accion = @@frm_accion;
$comentario = @@frm_comentario;
		
	if($accion == 'FINALIZAR'){
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Una vez analizado en caso en referencia, adjuntamos la decisión del mismo:</p>';
		$texto .= '<p align="justify">'.$comentario.'</p>';
		@@tri_texto_mail = $texto;
	}

$plantilla_rec = 'Plantilla_mail.html';

@@envio_mail_t1 = PMFSendMessage(@@APPLICATION,$de,$para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
$texto));

break;
}