<?php
/*******************************************************
*
* Generated by ProcessMaker Trigger Wizard
* Library: ProcessMaker Functions
* Method: PMF Send Message
* Date: 2020-08-30 10:35:06
*
* ProcessMaker 2020
*
*******************************************************/

$app_number = @@APP_NUMBER;
$tipo_req = @@frm_datosSolicitud_tipo_label;

$de = 'BPM Equisuiza';

// destinatarios
$para = 'daniel.villano@beesmart.ec';
$cc   = 'daniel.villano@beesmart.ec';
$bcc  = 'daniel.villano@beesmart.ec';

// lista de plantillas que quieres enviar
$plantillas = [
'emailEvent_1704315290593.html',		
'emailEvent_1704317602118.html',	
'emailEvent_1704693166308.html',		
'emailEvent_1704696025168.html',		
'emailEvent_1704772466543.html',		
'emailEvent_1705445513734.html',		
'emailEvent_1705474264069.html',		
'emailEvent_1706107623259.html',		
'emailEvent_1708635306692.html',		
'emailEvent_1709262774567.html',
'emailEvent_1709528774682.html',
'emailEvent_1716182165168.html',
'emailEvent_1716182411307.html'
];

// mensaje base
$texto = '<p align="justify">Estimado(a), Colaborador</p>';
$texto .= '<p align="justify">Se le notifica que se requiere la asignación del caso ' . $app_number . 
          ' de tipo ' . $tipo_req . 
          ' para su realización, por favor gestionarlo de acuerdo a las condiciones solicitadas</p>';

// recorrer todas las plantillas y enviarlas
foreach ($plantillas as $plantilla) {
    $asunto = $plantilla . " " . $app_number;

    @@envio_mail_t1 = PMFSendMessage(
        @@APPLICATION,
        $de,
        $para,
        $cc,
        $bcc,
        $asunto,
        $plantilla,
        array('tri_texto_mail' => $texto)
    );

    echo "Correo enviado con plantilla: " . $plantilla . "<br>";
}

// no usar die si quieres que siga corriendo
die;

