<?php
/*******************************************************
 *
 * Generated by ProcessMaker Trigger Wizard
 * Library: ProcessMaker Functions
 * Method: PMF Send Message
 * Date: 2020-08-30 10:35:06
 *
 * ProcessMaker 2020
 *
 *******************************************************/

$app_number = @@APP_NUMBER;
$tipo_req = @@frm_datosSolicitud_tipo_label;

//catalogo correos
$user = @@USER_LOGGED;
$sql = "SELECT USR_EMAIL MAIL FROM USERS WHERE USR_UID  = '$user'";
$resultadoCorreos = executeQuery($sql);
$responsable_emision_mail = $resultadoCorreos[1]['MAIL'];
$cc = $resultadoCorreos[1]['CAMPO2'];

if (@@frm_responsable_emision_mail == '') {
	@@frm_responsable_emision_mail = $responsable_emision_mail;
}


//validacion por tarea
switch (@@TASK) {
	//tarea 1
	case '48360598365087da6d339e4002983703':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		//$para = 'jcchachalo@gmail.com';

		$bcc = '';
		$asunto = "Notificación de caso en BPM $app_number";
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que se requiere la asignación del caso ' . $app_number . ' de tipo
	' . $tipo_req . ' para su realización, por favor gestionarlo de acuerdo a las condiciones solicitadas</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;
	//tarea 1
	case '520685045654466e9133299029687429':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		//$para = 'jcchachalo@gmail.com';

		$bcc = '';
		$asunto = "Notificación de caso en BPM $app_number";
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que se requiere la asignación del caso ' . $app_number . ' de tipo
	' . $tipo_req . ' para su realización, por favor gestionarlo de acuerdo a las condiciones solicitadas</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;
	//tarea 2
	case '22042344565087da6e310f3013718832':
		$de = '';
		$para = @@frm_responsable_suscripcion_mail;
		//$para = 'jcchachalo@gmail.com';
		$cc = @@frm_responsable_emision_mail;
		$bcc = 'pguevara@segurosequinoccial.com';
		$asunto = "Notificación de caso en BPM $app_number";
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que tiene asignado el caso ' . $app_number . ' de tipo
	' . $tipo_req . ' para su cotización en su bandeja, por favor gestionarlo de acuerdo a las condiciones solicitadas.
	</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;
	//tarea 2 C
	case '31382453465260bfbf23736093595618':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		//$para = 'jcchachalo@gmail.com';

		$bcc = '';
		$asunto = "Notificación de caso en BPM $app_number";
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que tiene asignado el caso ' . $app_number . ' de tipo
	' . $tipo_req . ' para su cotización en su bandeja, por favor gestionarlo de acuerdo a las condiciones solicitadas.
	</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;
	//tarea 3
	case '37352285165139885e35c51082282227':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		//$para = 'jcchachalo@gmail.com';

		$bcc = '';
		$asunto = "Notificación de caso en BPM $app_number";
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que tiene asignado un caso ' . $app_number . ' de aprobación MDA de tipo
	' . $tipo_req . ' , para aprobación de cotización (es) que serán remitidas a comercial para su presentación, por favor
	gestionarlo.s</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;
	//tarea 4
	case '646337226651398d5d9ee76046801370':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		//$para = 'jcchachalo@gmail.com';
		$cc = @@frm_responsable_comercial_mail;
		$bcc = 'pguevara@segurosequinoccial.com';
		$asunto = "Notificación de caso en BPM $app_number";
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que la solicitud del caso ' . $app_number . ' de tipo
	' . $tipo_req . ' fue exitosa parte del equipo Técnico. Por favor remitirse a su bandeja para que pueda presentar dicha
	(s) cotización (es) al prospecto.</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));
		break;
	//tarea 4.1 t
	case '187338637651f711d5d3d58092490594':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		//$para = 'jcchachalo@gmail.com';
		$cc = @@frm_responsable_comercial_mail;
		$bcc = 'pguevara@segurosequinoccial.com';
		$asunto = "Notificación de caso en BPM $app_number";
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que la solicitud del caso ' . $app_number . ' de tipo
	' . $tipo_req . ' fue exitosa parte del equipo Comercial. Por favor remitirse a su bandeja para que pueda presentar
	dicha (s) cotización (es) al prospecto.</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));
		break;
	//tarea 5
	case '25600274965087f36d030a4024877936':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		//$para = 'jcchachalo@gmail.com';

		$bcc = '';
		$asunto = "Notificación de caso en BPM $app_number";
		$accion = @@frm_accion;
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';

		if ($accion == "CONTINUAR") {
			$texto .= '<p align="justify">Se le notifica que el caso ' . $app_number . ' de tipo
	' . $tipo_req . ' fue aceptado por el cliente y se necesita que el Formulario de Vinculación este firmado y lleno por parte del cliente</tipo>
</p>';
		} else if ($accion == "FINALIZAR") {
			$texto .= '<p align="justify">Se le notifica que el caso ' . $app_number . ' de tipo
	' . $tipo_req . ' fue rechazado por el cliente y se dio de baja el caso</tipo>
</p>';
		} else {
			$texto .= '<p align="justify">Se le notifica que el caso ' . $app_number . ' de tipo
	' . $tipo_req . ' requiere de una revisión de cotización y fue asignado a su bandeja, por favor gestionarlo de acuerdo a
	las condiciones solicitadas.
	</tipo>
</p>';
		}

		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;

	//tarea 6
	case '407718691650882be398cf4039245263':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		//$para = 'jcchachalo@gmail.com';

		$bcc = '';
		$asunto = "Notificación de caso en BPM $app_number";
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que tiene asignado el caso ' . $app_number . ' de aprobación MDA, para
	aprobación de recotización (es) que serán remitidas a comercial para su presentación, por favor gestionarlo.
	</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;

	//tarea 6.1
	case '24837568665207b0bab49f3075876637':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		//$para = 'jcchachalo@gmail.com';

		$bcc = '';
		$asunto = "Notificación de caso en BPM $app_number";
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que tiene asignado el caso ' . $app_number . ' de aprobación MDA, para
	aprobación de recotización (es) que serán remitidas a comercial para su presentación, por favor gestionarlo.
	</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;

	//tarea 7
	case '40520168265139c1fe781b2082871872':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		//$para = 'jcchachalo@gmail.com';

		$bcc = '';
		$asunto = "Notificación de caso en BPM $app_number";
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que el caso ' . $app_number . ' fue aprobado y remitido al ejecutivo comercial
	correspondiente para su presentación al cliente.
	</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;

	//tarea 7.1 T
	case '27227951165207a1bac3907053331729':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		//$para = 'jcchachalo@gmail.com';

		$bcc = '';
		$asunto = "Notificación de caso en BPM $app_number";
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que el caso ' . $app_number . ' fue aprobado y remitido al ejecutivo comercial
	correspondiente para su presentación al cliente.
	</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;

	//tarea 2.1
	case '78562928365087da6ddd068062972905':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		//$para = 'jcchachalo@gmail.com';

		$bcc = '';
		$asunto = "Notificación de caso en BPM $app_number";
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que el caso ' . $app_number . ' de tipo
	' . $tipo_req . ' fue aceptado por el cliente y se dio su paso a Emisión de acuerdo a las siguientes condiciones.
	</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;
	//tarea 8
	case '73169901865139ce82b0d98098087063':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		//$para = 'jcchachalo@gmail.com';

		$bcc = '';
		$asunto = "Notificación de caso en BPM $app_number";
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que tiene asignado el caso ' . $app_number . ' en  su bandeja, por favor gestionarlo de acuerdo a las condiciones solicitadas.
</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;
	//tarea 9
	case '24268372265087e46d019c6030896197':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		//$para = 'jcchachalo@gmail.com';

		$bcc = '';
		$asunto = "Notificación de caso en BPM $app_number";
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que la solicitud de revisión borrador del caso ' . $app_number . ' fue exitosa
	por favor revisar el documento para que pueda ser enviado a comercial.
	</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;
	//tarea 10
	case '59758233765139e2bb13f80066822696':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		//$para = 'jcchachalo@gmail.com';

		$bcc = '';
		$asunto = "Notificación de caso en BPM $app_number";
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que la solicitud de revisión borrador del caso ' . $app_number . ' fue exitosa
	por favor gestionarlo de acuerdo a las condiciones solicitadas.
	</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;
	//tarea 11
	case '16795713665139e7c0cb214066895796':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		//$para = 'jcchachalo@gmail.com';

		$bcc = '';
		$asunto = "Notificación de caso en BPM $app_number";
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que la solicitud de revisión borrador del caso ' . $app_number . ' fue exitosa
	por favor gestionarlo de acuerdo a las condiciones solicitadas.
	</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;
	//tarea 12
	case '72313372665139ea474c889058922722':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		//$para = 'jcchachalo@gmail.com';

		$bcc = '';
		$asunto = "Notificación de caso en BPM $app_number";
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que la solicitud de emisión del caso ' . $app_number . ' fue exitosa por favor
	revisar y aprobar emisión.</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;
	//tarea 13
	case '75557425865139ecc83cd31064722953':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		//$para = 'jcchachalo@gmail.com';

		$bcc = '';
		$asunto = "Notificación de caso en BPM $app_number";
		$accion = @@frm_accion;
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';

		if ($accion == "CONTINUAR") {
			$texto .= '<p align="justify">Se le notifica que la solicitud de emisión del caso ' . $app_number . ' fue exitosa y enviada
	al cliente.</tipo>
</p>';
		} else {
			$texto .= '<p align="justify">Se le notifica que la solicitud de emisión del caso ' . $app_number . ' requiere su atneción
	en lo siguiente:
	*Observaciones* por favor gestionarlo de acuerdo a las condiciones solicitadas.
	</tipo>
</p>';
		}

		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;
}
