<?php
/*******************************************************
 *
 * Generated by ProcessMaker Trigger Wizard
 * Library: ProcessMaker Functions
 * Method: PMF Send Message
 * Date: 2020-08-30 10:35:06
 *
 * ProcessMaker 2020
 *
 *******************************************************/

$app_number = @@APP_NUMBER;
$tipo_req = @@frm_datosSolicitud_tipo_label;
$taller = @@frm_taller;
$server = @@URL_SERVER_SQL;


$sqlCorreos = "SELECT ac.CAMPO1 ,ac.CAMPO2 FROM   ADMIN_CATALOGOS ac WHERE ac.COD_CATALOGO = 'COPIAS_MAIL' AND ac.INTEGRACION = '76661804465655b4bdffbc2081200894'
AND ac.DESCRIPCION ='Envio_correos' LIMIT 1";

$resultadoCorreos = executeQuery($sqlCorreos);

$cc = $resultadoCorreos[1]['CAMPO2'];
$bcc = $resultadoCorreos[1]['CAMPO1'];

switch (@@TASK) {
	//tarea 1
	case '47793586864a1915c3740e7013393106':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		$para = @@tri_correo_desarrollador_cc;


		$asunto = "Notificación de caso en BPM " . @#APP_NUMBER;
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que se requiere la asignación del caso ' . $app_number . ' de tipo
	' . $tipo_req . ' para su realización, por favor gestionarlo de acuerdo a las condiciones solicitadas</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;
	//tarea 2
	case '21947251964a193141bc7e8005186014':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		$para = @@tri_correo_desarrollador_cc;


		$asunto = "Notificación de caso en BPM " . @#APP_NUMBER;
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que el caso ' . $app_number . ' atendido por el taller
	' . $taller . ' fue revisado, por favor darle el seguimiento necesario.
	</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;

	//T2: Analizar Coberturas Siniestro
	case '72144115864a1924c5ab549003287587':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		$para = @@tri_correo_desarrollador_cc;


		$asunto = "Notificación de caso en BPM " . @#APP_NUMBER;
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$aAttachments = array();
		$accion = @@frm_accion;
		$caseID = @@APPLICATION;
		if ($accion == "ESPERAR") {
			$texto .= '<p align="justify">Se le notifica que el caso ' . $app_number . ' fue mantenido en su bandeja</tipo>
</p>';
		} elseif ($accion == "CONTINUAR") {

			$outputUID = '563796961654b0c94578a15070715888';
			$sql = "SELECT
  MAX(DOC_VERSION) AS MAX_VERSION, APP_DOC_UID
FROM
  APP_DOCUMENT where APP_UID = '$caseID'
  					 and APP_DOC_TYPE = 'OUTPUT' and DOC_UID = '$outputUID'";
			$res = executeQuery($sql);
			$docUID = $res['1']['APP_DOC_UID'];
			$v = $res['1']['MAX_VERSION'];

			//Creo link de archivo
			$server =  $server . '/syscertificacion/es/3sesa/cases/cases_ShowOutputDocument?a=' . $docUID . '&v=' . $v . '&ext=pdf';
			$niv1 = substr($caseID, 0, 3);
			$niv2 = substr($caseID, 3, 3);
			$niv3 = substr($caseID, 6, 3);
			$niv4 = substr($caseID, 9);

			$doc_logico = '/opt/processmaker/shared/sites/workflow/files' . PATH_SEP . $niv1 . PATH_SEP . $niv2 . PATH_SEP . $niv3 . PATH_SEP . $niv4 . PATH_SEP . 'outdocs/' . $docUID . '_' . $v . '.pdf';

			@@tri_link_certificado = $server;

			$aAttachments = PMFAddAttachmentToArray($aAttachments, basename($doc_logico), $doc_logico);

			@@tri_mail_certificado = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array(), $aAttachments);

			$texto .= '<p align="justify">Se le notifica que el caso ' . $app_number . ' pasó a revisión</tipo>
</p>';
		} else {
			$texto .= '<p align="justify">Se le notifica que su caso necesita información adicional
	</tipo>
</p>';
		}
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto), $aAttachments);

		break;


	//T2.1: Realizar Gestion Siniestro Cliente
	case '1346005026526fac1a91d03001561073':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		$para = @@tri_correo_desarrollador_cc;


		$asunto = "Notificación de caso en BPM " . @#APP_NUMBER;
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que el caso ' . $app_number . ' fue devuelto por el cliente / broker con la información solicitada
	</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;
	//tarea 3
	case '2579012976503be0b08c3b6090809481':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		$para = @@tri_correo_desarrollador_cc;


		$asunto = "Notificación de caso en BPM " . @#APP_NUMBER;
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que el caso ' . $app_number . ' fue atendido por MUNDO PARTES para su análisis
	y cotización, por favor darle el seguimiento necesario.
	</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;
	//tarea 4
	case '56594959064f8a7036237e1042256890':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		$para = @@tri_correo_desarrollador_cc;


		$asunto = "Notificación de caso en BPM " . @#APP_NUMBER;
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		if ($accion == "VERIFICAR") {
			$texto .= '<p align="justify">Se le notifica que el caso ' . $app_number . ' fue asignado a su bandeja para revisión del ajustador interno</tipo>
</p>';
		} elseif ($accion == "CONTINUAR") {
			$texto .= '<p align="justify">Se le notifica que el caso ' . $app_number . ' fue asignado a su bandeja para revisión del PDA</tipo>
</p>';
		} elseif ($accion == "SOLICITAR") {
			$texto .= '<p align="justify">Se le notifica que el caso ' . $app_number . ' requiere de mas información</tipo>
</p>';
		} elseif ($accion == "ACTUALIZAR") {
			$texto .= '<p align="justify">Se le notifica que el caso ' . $app_number . ' fue asignado a su bandeja</tipo>
</p>';
		} elseif ($accion == "REQUERIR") {
			$texto .= '<p align="justify">Se le notifica que el caso ' . $app_number . ' requiere de peritaje especial</tipo>
</p>';
		} elseif ($accion == "SUSTITUIR") {
			$texto .= '<p align="justify">Se le notifica que el caso ' . $app_number . ' requiere de un auto sustituto</tipo>
</p>';
		} elseif ($accion == "PERDER") {
			$texto .= '<p align="justify">Se le notifica que el caso ' . $app_number . ' fue enviado al proceso de perdida total</tipo>
</p>';
		} elseif ($accion == "APROBAR") {
			$texto .= '<p align="justify">Se le notifica que el caso ' . $app_number . ' fue enviado a aprobación de la carta de deducible</tipo>
</p>';
		} elseif ($accion == "NEGAR") {
			$texto .= '<p align="justify">Se le notifica que el caso ' . $app_number . ' requiere de la generación de una carta de negativa</tipo>
</p>';
		} elseif ($accion == "FINALIZAR") {
			$texto .= '<p align="justify">Se le notifica que el caso ' . $app_number . ' fue enviado al proceso de cierre administrativo</tipo>
</p>';
		} else {
			$texto .= '<p align="justify">Se le notifica que su caso necesita información adicional
	</tipo>
</p>';
		}
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));
		break;
	//tarea 2.1  reasing t
	case '2429365746526b8e3ce1692043508776':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		$para = @@tri_correo_desarrollador_cc;


		$asunto = "Notificación de caso en BPM " . @#APP_NUMBER;
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que la solicitud del caso ' . $app_number . ' de tipo
	' . $tipo_req . ' fue exitosa parte del equipo Comercial. Por favor remitirse a su bandeja para que pueda presentar
	dicha (s) cotización (es) al prospecto.</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));
		break;
	//T5: Adjuntar Información del Siniestro
	case '54026307264a1947c2ccb33085557235':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		$para = @@tri_correo_desarrollador_cc;


		$asunto = "Notificación de caso en BPM " . @#APP_NUMBER;
		$accion = @@frm_accion;
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';

		if ($accion == "CONTINUAR") {
			$texto .= '<p align="justify">Se le notifica que el caso ' . $app_number . ' de tipo
	' . $tipo_req . ' fue aceptado por el cliente y se necesita que el Formulario de Vinculación este firmado y lleno por parte del cliente</tipo>
</p>';
		} elseif ($accion == "FINALIZAR") {
			$texto .= '<p align="justify">Se le notifica que el caso ' . $app_number . ' de tipo
	' . $tipo_req . ' fue rechazado por el cliente y se dio de baja el caso</tipo>
</p>';
		} else {
			$texto .= '<p align="justify">Se le notifica que el caso ' . $app_number . ' de tipo
	' . $tipo_req . ' requiere de una revisión de cotización y fue asignado a su bandeja, por favor gestionarlo de acuerdo a
	las condiciones solicitadas.
	</tipo>
</p>';
		}

		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;

	//T2: Validar Información Siniestro - Comercial
	case '14286117264a1924c53d4c0063435298':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		$para = @@tri_correo_desarrollador_cc;


		$asunto = "Notificación de caso en BPM " . @#APP_NUMBER;
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que tiene asignado el caso ' . $app_number . ' de aprobación MDA, para
	aprobación de recotización (es) que serán remitidas a comercial para su presentación, por favor gestionarlo.
	</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;

	//T2: Validar Información Siniestro - Comercial
	case '5075995886526b01d838ef4015318307':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		$para = @@tri_correo_desarrollador_cc;


		$asunto = "Notificación de caso en BPM " . @#APP_NUMBER;
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que tiene asignado el caso ' . $app_number . ' de aprobación MDA, para
	aprobación de recotización (es) que serán remitidas a comercial para su presentación, por favor gestionarlo.
	</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;

	//T3: Revisar Información Cartera del siniestro
	case '27398367464a1974c31cb78042429959':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		$para = @@tri_correo_desarrollador_cc;


		$asunto = "Notificación de caso en BPM " . @#APP_NUMBER;
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que tiene asignado el caso ' . $app_number . ' de aprobación MDA, para
	aprobación de recotización (es) que serán remitidas a comercial para su presentación, por favor gestionarlo.
	</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;


	//T5: Registro de datos de los repuestos
	case '855535701652eaa2e18e1f2066505597':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		$para = @@tri_correo_desarrollador_cc;


		$asunto = "Notificación de caso en BPM " . @#APP_NUMBER;
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que tiene asignado el caso ' . $app_number . ' de aprobación MDA, para
	aprobación de recotización (es) que serán remitidas a comercial para su presentación, por favor gestionarlo.
	</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;


	//T5: Aprobar ajustador Externo
	case '855535701652eaa2e18e1f2066505597':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		$para = @@tri_correo_desarrollador_cc;


		$asunto = "Notificación de caso en BPM " . @#APP_NUMBER;
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que tiene asignado el caso ' . $app_number . ' de aprobación MDA, para
	aprobación de recotización (es) que serán remitidas a comercial para su presentación, por favor gestionarlo.
	</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;

	//T5: Aprobar daños del siniestro
	case '68284694964f8a843632370070752291':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		$para = @@tri_correo_desarrollador_cc;


		$asunto = "Notificación de caso en BPM " . @#APP_NUMBER;
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que tiene asignado el caso ' . $app_number . ' de aprobación MDA, para
	aprobación de recotización (es) que serán remitidas a comercial para su presentación, por favor gestionarlo.
	</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;


	//T5: Verificar daños del siniestro
	case '63199860364a1956c302338036694005':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		$para = @@tri_correo_desarrollador_cc;


		$asunto = "Notificación de caso en BPM " . @#APP_NUMBER;
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que tiene asignado el caso ' . $app_number . ' de aprobación MDA, para
	aprobación de recotización (es) que serán remitidas a comercial para su presentación, por favor gestionarlo.
	</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;

	//T5: Aprobar Siniestro
	case '46680647864a194cc1ea273036601085':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		$para = @@tri_correo_desarrollador_cc;


		$asunto = "Notificación de caso en BPM " . @#APP_NUMBER;
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		if (@@frm_accion == "CONTINUAR") {
			$texto .= '<p align="justify">Se le notifica que el caso ' . $app_number . ' fue aprobado para el inicio de la reparación
	</tipo>
</p>';
		}
		if (@@frm_accion == "RECHAZAR") {
			$texto .= '<p align="justify">Se le notifica que el caso ' . $app_number . ' fue rechazado y devuelto a su bandeja
	</tipo>
</p>';
		}

		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;

	//T5.1 Compra de los repuestos / Taller
	case '889550067654129ffcd4c26047533019':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		$para = @@tri_correo_desarrollador_cc;


		$asunto = "Notificación de caso en BPM " . @#APP_NUMBER;
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica MUNDO PARTES realizó el proceso de compra de los repuestos del caso ' . $app_number . ', por favor gestionarlo.
	</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;

	//T6: Recepción de repuestos
	case '43250165965412ac7d66884088453364':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		$para = @@tri_correo_desarrollador_cc;


		$asunto = "Notificación de caso en BPM " . @#APP_NUMBER;
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		if ($accion == "CONTINUAR") {
			$texto .= '<p align="justify">Se le notifica que todos los repuestos del caso ' . $app_number . '
	fueron recibidos de forma correcta.</tipo>
</p>';
		}
		if ($accion == "REGRESAR") {
			$texto .= '<p align="justify">Se le notifica que los repuestos del caso ' . $app_number . '
	presentan alguna novedad.</tipo>
</p>';
		} else {
			$texto .= '<p align="justify">Se le notifica que los repuestos del caso ' . $app_number . '
	fueron recibidos de forma parcial.</tipo>
</p>';
		}

		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;

	//T6: Verificar daños del siniestro Externo
	case '97599337664f8a8fb544ba6077513094':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		$para = @@tri_correo_desarrollador_cc;


		$asunto = "Notificación de caso en BPM " . @#APP_NUMBER;
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que tiene asignado el caso ' . $app_number . ' de aprobación MDA, para
	aprobación de recotización (es) que serán remitidas a comercial para su presentación, por favor gestionarlo.
	</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;

	//T6: Verificar daños del siniestro Externo
	case '74204951465270061a3a591051089497':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		$para = @@tri_correo_desarrollador_cc;


		$asunto = "Notificación de caso en BPM " . @#APP_NUMBER;
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que tiene asignado el caso ' . $app_number . ' de aprobación MDA, para
	aprobación de recotización (es) que serán remitidas a comercial para su presentación, por favor gestionarlo.
	</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;

	//tarea 6
	case '74725028464a1963426ccd7096187892':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		$para = @@tri_correo_desarrollador_cc;


		$asunto = "Notificación de caso en BPM " . @#APP_NUMBER;
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que el caso ' . $app_number . ' fue aprobado y remitido al ejecutivo comercial
	correspondiente para su presentación al cliente.
	</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;
	//T6: Revisar Información de la negativa
	case '9148285416526b22bd12785076248090':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		$para = @@tri_correo_desarrollador_cc;


		$asunto = "Notificación de caso en BPM " . @#APP_NUMBER;
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que el caso ' . $app_number . ' fue aprobado y remitido al ejecutivo comercial
	correspondiente para su presentación al cliente.
	</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;
	//T7: Adjunte el finiquito
	case '5012526796503c65306a0f1027793854':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		$para = @@tri_correo_desarrollador_cc;


		$asunto = "Notificación de caso en BPM " . @#APP_NUMBER;
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que el caso ' . $app_number . ' fue aprobado y remitido al ejecutivo comercial
	correspondiente para su presentación al cliente.
	</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;

	//T7: Aprobar Carta de negativa
	case '8918106796526b2cbbf8677016141095':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		$para = @@tri_correo_desarrollador_cc;


		$asunto = "Notificación de caso en BPM " . @#APP_NUMBER;
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que el caso ' . $app_number . ' fue aprobado y remitido al ejecutivo comercial
	correspondiente para su presentación al cliente.
	</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;

	//tarea 5 negativas
	case '4409057566526b0c3cd7896010697770':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		$para = @@tri_correo_desarrollador_cc;


		$asunto = "Notificación de caso en BPM " . @#APP_NUMBER;
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que el caso ' . $app_number . ' de tipo
	' . $tipo_req . ' fue aceptado por el cliente y se dio su paso a Emisión de acuerdo a las siguientes condiciones.
	</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;
	//tarea 5.1
	case '8853055126526b18bca33a0006984500':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		$para = @@tri_correo_desarrollador_cc;


		$asunto = "Notificación de caso en BPM " . @#APP_NUMBER;
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que tiene asignado el caso ' . $app_number . ' en  su bandeja, por favor gestionarlo de acuerdo a las condiciones solicitadas.
</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;
	//tarea 9
	case '24268372265087e46d019c6030896197':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		$para = @@tri_correo_desarrollador_cc;


		$asunto = "Notificación de caso en BPM " . @#APP_NUMBER;
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que la solicitud de revisión borrador del caso ' . $app_number . ' fue exitosa
	por favor revisar el documento para que pueda ser enviado a comercial.
	</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;
	//tarea 10
	case '59758233765139e2bb13f80066822696':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		$para = @@tri_correo_desarrollador_cc;


		$asunto = "Notificación de caso en BPM " . @#APP_NUMBER;
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que la solicitud de revisión borrador del caso ' . $app_number . ' fue exitosa
	por favor gestionarlo de acuerdo a las condiciones solicitadas.
	</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;
	//tarea 11
	case '16795713665139e7c0cb214066895796':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		$para = @@tri_correo_desarrollador_cc;


		$asunto = "Notificación de caso en BPM " . @#APP_NUMBER;
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que la solicitud de revisión borrador del caso ' . $app_number . ' fue exitosa
	por favor gestionarlo de acuerdo a las condiciones solicitadas.
	</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;
	//tarea 12
	case '72313372665139ea474c889058922722':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		$para = @@tri_correo_desarrollador_cc;


		$asunto = "Notificación de caso en BPM " . @#APP_NUMBER;
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que la solicitud de emisión del caso ' . $app_number . ' fue exitosa por favor
	revisar y aprobar emisión.</tipo>
</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;
	//tarea 13
	case '75557425865139ecc83cd31064722953':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		$para = @@tri_correo_desarrollador_cc;


		$asunto = "Notificación de caso en BPM " . @#APP_NUMBER;
		$accion = @@frm_accion;
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';

		if ($accion == "CONTINUAR") {
			$texto .= '<p align="justify">Se le notifica que la solicitud de emisión del caso ' . $app_number . ' fue exitosa y enviada
	al cliente.</tipo>
</p>';
		} else {
			$texto .= '<p align="justify">Se le notifica que la solicitud de emisión del caso ' . $app_number . ' requiere su atneción
	en lo siguiente:
	*Observaciones* por favor gestionarlo de acuerdo a las condiciones solicitadas.
	</tipo>
</p>';
		}

		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;

	default:

		$de = '';
		$para = @@tri_correo_desarrollador_cc;


		$asunto = "Notificación de caso en BPM " . @#APP_NUMBER;
		$accion = @@frm_accion;
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';

		if ($accion == "CONTINUAR") {
			$texto .= '<p align="justify">Se le notifica que la solicitud de emisión del caso ' . $app_number . ' fue exitosa y enviada
		al cliente.</tipo>
	</p>';
		} else {
			$texto .= '<p align="justify">Se le notifica que la solicitud de emisión del caso ' . $app_number . ' requiere su atneción
		en lo siguiente:
		*Observaciones* por favor gestionarlo de acuerdo a las condiciones solicitadas.
		</tipo>
	</p>';
		}

		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

		break;
}
