<?php
/*******************************************************
 *
 * Generated by ProcessMaker Trigger Wizard
 * Library: ProcessMaker Functions
 * Method: PMF Send Message
 * Date: 2020-08-30 10:35:06
 *
 * ProcessMaker 2020
 *
 *******************************************************/

$texto = 'Notificacion de solicitud de Prestamos y retiros';

//ENVIO DE EMAIL

$de = '';

$para = @@tri_user_sac_mail;


$host = @@URL_SERVER_SQL;
@@adrr_server =  $host;

$cc = 'se_mlopez@segurosequinoccial.com';
$bcc = '';
$asunto = "Notificion confirmacion de solicitud " . @#frm_tipo_solicitud_label;

$plantilla_rec = 'Confirmacion_EJRetencion.html';

@@envio_mail = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('texto' => $texto, 'adrr_server' => @@adrr_server));

