<?php
/*******************************************************
 *
 * Generated by ProcessMaker Trigger Wizard
 * Library: ProcessMaker Functions
 * Method: PMF Send Message
 * Date: 2020-08-30 10:35:06
 *
 * ProcessMaker 2020
 *
 *******************************************************/

$texto = 'Confirmacion de solicitud de Prestamos y retiros';

//ENVIO DE EMAIL


$host = @@URL_SERVER_SQL;
@@adrr_server =  $host;

$de = '';

$para = @@frm_correo_electronico_receptor;

//$cc = 'victor.cortez@beesmart.ec';
$cc = '';
$bcc = '';
$asunto = "Notificion confirmacion de solicitud " . @#frm_tipo_solicitud_label;

$plantilla_rec = 'Confirmacion_Solicitud.html';

@@envio_mail = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('texto' => $texto, 'adrr_server' => @@adrr_server));

