<?php
/*******************************************************
 *
 * Generated by ProcessMaker Trigger Wizard
 * Library: ProcessMaker Functions
 * Method: Get Current Date
 * Date: 2020-08-30 10:28:13
 *
 * ProcessMaker 2020
 *
 *******************************************************/

@@frm_fecha_finalizacion = getCurrentDate().' '.getCurrentTime();