<?php
/*******************************************************
 *
 * Generated by ProcessMaker Trigger Wizard
 * Library: ProcessMaker Functions
 * Method: Get Current Date
 * Date: 2020-08-30 10:28:13
 *
 * ProcessMaker 2020
 *
 *******************************************************/

$cnx = '4647520625f3ca6ed2d2621030136501';

@@frm_fecha_creacion = getCurrentDate().' '.getCurrentTime();

$sql = "SELECT
  CODIGO,
  DESCRIPCION
FROM
  ADMIN_CATALOGOS
WHERE COD_CATALOGO = 'MONTOS_MINIMOS'
AND ESTADO = '1'";

$rs = executeQuery($sql, $cnx);

if(is_array($rs)){
	foreach($rs as $data){
		if ($data['CODIGO'] == 'PRESTAMO')
			@@tri_monto_minimo_p = $data['DESCRIPCION'];
		if ($data['CODIGO'] == 'RETIRO')
			@@tri_monto_minimo_r = $data['DESCRIPCION'];
	}
}

@@tri_user_sac = @@USER_LOGGED;

$sql = "SELECT USR_EMAIL FROM USERS WHERE USR_UID = '".@@tri_user_sac."'";
$rs = executeQuery($sql);

@@tri_user_sac_mail = $rs['1']['USR_EMAIL'];
@@cod_usuario_fun = @@USR_USERNAME;
