<?php
/*******************************************************
*
* Generated by ProcessMaker Trigger Wizard
* Library: ProcessMaker Functions
* Method: PMF Send Message
* Date: 2020-08-30 10:35:06
*
* ProcessMaker 2020
*
*******************************************************/

$app_number = @@APP_NUMBER;
$tipo_req = @@frm_datosSolicitud_tipo_label;

$sqlCorreos = "SELECT ac.CAMPO2 FROM ADMIN_CATALOGOS ac WHERE ac.COD_CATALOGO = 'COPIAS_MAIL' AND ac.INTEGRACION = '8799375496521525608b1c5005115762'
AND ac.DESCRIPCION ='Envio_correos' LIMIT 1";

$resultadoCorreos = executeQuery($sqlCorreos);

$cc = $resultadoCorreos[1]['CAMPO2'];
switch (@@TASK){
	//tarea 1
	case '47159097865216c17422f85064227461':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		$bcc = '';
		$asunto = "Notificación de caso en BPM ". @#APP_NUMBER;
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que se requiere la asignación del caso '.$app_number.' de tipo
			'.$tipo_req.' para su realización, por favor gestionarlo de acuerdo a las condiciones solicitadas</tipo>
		</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION,$de,$para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

	break;
	//tarea 2
	case '17077449865216c3f3d71e5057347607':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		$bcc = '';
		$asunto = "Notificación de caso en BPM ". @#APP_NUMBER;
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que tiene asignado el caso '.$app_number.' de tipo
			'.$tipo_req.' para su resolución en su bandeja, por favor gestionarlo de acuerdo a las condiciones solicitadas.
			</tipo>
		</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION,$de,$para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

	break;
	//tarea 3
	case '27724906265216c8f395922053571348':
		$de = '';
		$para = @@frm_responsable_emision_mail;
		$bcc = '';
		$asunto = "Notificación de caso en BPM ". @#APP_NUMBER;
		$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
		$texto .= '<p align="justify">Se le notifica que tiene asignado un caso '.$app_number.' de tipo
			'.$tipo_req.' , su ejecución en su bandeja, por favor gestionarlo de acuerdo a las condiciones solicitadas.</tipo>
		</p>';
		$comentario = @@frm_comentario;
		$accion = @@frm_accion;
		$plantilla_rec = 'Plantilla_mail.html';

		@@envio_mail_t1 = PMFSendMessage(@@APPLICATION,$de,$para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
		$texto));

	break;
}
