<?php
/*******************************************************
 *
 * Generated by ProcessMaker Trigger Wizard
 * Library: ProcessMaker Functions
 * Method: PMF Send Message
 * Date: 2020-08-30 10:35:06
 *
 * ProcessMaker 2020
 *
 *******************************************************/

$texto = 'Error de solicitud de Cambio de Conducto';

//ENVIO DE EMAIL

$de = '';

$para = 'infoequivida@segurosequinoccial.com';

$host = @@URL_SERVER_SQL;

@@adrr_server = $host;

$cc = '';
$bcc = '';
$asunto = "Notificación error de solicitud " . @#frm_tipo_solicitud_label;

$plantilla_rec = 'Error_Solicitud.html';

@@envio_mail = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('texto' => $texto, 'adrr_server' => @@adrr_server));

