<?php
 
/*******************************************************
*
* Generated by ProcessMaker Trigger Wizard
* Library: ProcessMaker Functions
* Method: PMF Send Message
* Date: 2020-08-30 10:35:06
*
* ProcessMaker 2020
*cambio
*******************************************************/

$app_number = @@APP_NUMBER;

$tipo_req = @@frm_datosSolicitud_tipo_label;
//validacion por tarea
$de = 'NOTIFICACIONES BPM EQUISUIZA';
$para = @@frm_responsable_emision_mail;
$cc = 'pguevara@segurosequinoccial.com';
$cc = 'henry.bautista@beesmart.ec';
$bcc = '';
$asunto = "Notificación de caso en BPM ". @#APP_NUMBER;
$texto = '<p align="justify">Estimado(a),&nbsp;Colaborador</p>';
$texto .= '<p align="justify">Se le notifica que se requiere la asignación del caso '.$app_number.' de tipo
	'.$tipo_req.' para su realización, por favor gestionarlo de acuerdo a las condiciones solicitadas</tipo>
</p>';
$comentario = @@frm_comentario;
$accion = @@frm_accion;
$plantilla_rec = 'emailEvent_1608352416720.html';
		
$para = 'daniel.villano@beesmart.ec';
$cc = 'daniel.villano@beesmart.ec';
$bcc = ' daniel.villano@beesmart.ec';

@@envio_mail_t1 = PMFSendMessage(@@APPLICATION,$de,$para, $cc, $bcc, $asunto, $plantilla_rec, array('tri_texto_mail' =>
$texto));
die;

 