<?php
try{

    $pro_uid = @@PROCESS;
    $cnx = '11264850561d723f004d5c2072943786';
    $contratante = @@frm_tipo_contratante;

    $config = parse_ini_file('/code/shared/sites/certificacion/env.ini', true);
    @@URL_SERVER_SQL =  $config['configuracion_entorno']['url'];

    //Generar Reserva SiSe
    @@__ERROR__ = '';

    if(@@tri_bandera_alcance == ''){
        @@tri_id_stro = '';
        @@tri_nro_stro = '';
    }

    @@tri_bandera_grabado = '';
    @@tri_message_grabado = '';

    /*******************************************************
    *
    * Generated by ProcessMaker Trigger Wizard
    * Library: ProcessMaker Functions
    * Method: PMF Send Message
    * Date: 2020-08-30 10:35:06
    *
    * ProcessMaker 2020
    *
    *******************************************************/

    /* Recupera destinatarios de correo */
    $desPARA = '';
    $desCC = '';
    $desBCC = '';

    $sql_correo = "SELECT *
    FROM ADMIN_CATALOGOS WHERE
    PRO_UID = 'GENERICO'
    AND INTEGRACION = '820474191615f602d3c4b33049036948'
    AND DESCRIPCION = 'Consultar_user_sac_web'
    ";

    $rs_correo = executeQuery($sql_correo, $cnx);
    $desPARA = $rs_correo[1]['VALOR'];
    $desCC = $rs_correo[1]['CAMPO2'];
    $desBCC = $rs_correo[1]['CAMPO1'];



    //ENVIO DE EMAIL
    $texto = 'ERROR Creación de reserva de SINIESTRO';
    $de = '';
    //$para = 'jpvalenzuela@segurosequinoccial.com';
    //$cc = 'iportilla@segurosequinoccial.com';
    //$bcc='pcapuz@segurosequinoccial.com';
    $para = $desPARA;
    $cc = $desCC;
    $bcc = $desBCC;
    $asunto = "ERROR Creación de reserva de SINIESTRO ". @#APP_NUMBER;
    $plantilla_rec = 'Error_Resrerva.html';

    //USUARIO DE SAC RANDOM
    /*$sql = "SELECT USR_UID FROM GROUP_USER WHERE GRP_UID = '33894654261d657cab84992054520189' ORDER BY RAND() LIMIT 1";
    $rs = executeQuery($sql);
    $user_sac = $rs['1']['USR_UID'];
    */
    $user_sac = @@tri_user_sac;
    $sql_user = "SELECT USR_UID, USR_EMAIL FROM USERS WHERE USR_UID= '$user_sac'";
    $rs_user = executeQuery($sql_user);

    //@@tri_user_sac = $rs_user['1']['USR_UID'];
    @@tri_user_sac_mail = $rs_user['1']['USR_EMAIL'];

    //USUARIO AUDITOR
    $tri_user_auditor = @@tri_user_auditor;
    $sql_user_auid = "SELECT USR_UID, USR_EMAIL FROM USERS WHERE USR_UID = '$tri_user_auditor'";
    $rs_user_auid = executeQuery($sql_user_auid);

    @@tri_user_auditor_mail = $rs_user_auid['1']['USR_EMAIL'];
    $cc = @@tri_user_auditor_mail;

    @@bandera_web = 'true';
    @@tri_bandera_web = 'WEB';
    @@frm_canal_entrada = 'WEB';

    if(@@TASK != '5738766796298c3a3e33a08031379834'){
        @@tri_estado_evento = 1;
    }

    @@tri_fecha_registro_web = date('Y-m-d');
    @@frm_fecha_registro = date('Y-m-d');

    //EXPLODE DEL CAMPO POLIZAS
    $arr_poliza = explode('|',@@frm_polizas);

    @@frm_id_cns = $arr_poliza[0];
    @@frm_id_pv = $arr_poliza[1];
    @@frm_id_pv_cero = $arr_poliza[2];
    @@frm_cod_tercero = $arr_poliza[3];
    @@frm_cod_aseg = $arr_poliza[4];
    @@frm_nro_aseg = $arr_poliza[5];
    @@frm_nro_pariente = $arr_poliza[6];
    @@frm_numero_poliza = $arr_poliza[7];
    @@frm_ramo = $arr_poliza[8];
    @@frm_sucursal = $arr_poliza[9];
    @@frm_tipo_poliza = $arr_poliza[10];
    @@frm_linea_negocio = $arr_poliza[10];
    @@frm_fecha_ingreso_poliza = $arr_poliza[11];
    @@frm_fecha_ingreso_poliza_aux = $arr_poliza[11];
    @@frm_broker = $arr_poliza[12];
    @@frm_contratante = $arr_poliza[13];
    @@frm_contratante_identificacion = $arr_poliza[14];
    @@frm_poliza_NumCertificado = $arr_poliza[15];
    @@frm_poliza_ValidFrom = $arr_poliza[16];
    @@frm_poliza_ValidTo = $arr_poliza[17];

    //peso por monto
    $monto_reportado = @@frm_monto_reportado;
    //codigo de la tabla
    $sql = "SELECT CODIGO FROM ADMIN_CATALOGOS WHERE COD_CATALOGO = 'RANGO_MONTOS' AND PRO_UID = '$pro_uid' AND ESTADO = 1 AND VALOR <= $monto_reportado AND INTEGRACION > $monto_reportado ";
    $rs = executeQuery($sql, $cnx);
    @@tri_rango_monto = ($rs['1']['CODIGO'] == '' ? 0 : $rs['1']['CODIGO']);

    //peso por tipo de poliza
    $frm_tipo_poliza = @@frm_tipo_poliza;
    //codigo de la tabla
    $sql = "SELECT CODIGO FROM ADMIN_CATALOGOS WHERE COD_CATALOGO = 'RANGO_POLIZA' AND PRO_UID = '$pro_uid' AND ESTADO = 1 AND DESCRIPCION = '$frm_tipo_poliza'";
    $rs = executeQuery($sql, $cnx);
    @@tri_rango_poliza = ($rs['1']['CODIGO'] == '' ? 0 : $rs['1']['CODIGO']);

    //peso por cobertura madre
    $iaux = 'false';
    foreach(@=grd_coberturas as $datagrid_cober){
        if($datagrid_cober['grd_txt_aplicar'] == 'SI' && $iaux=='false'){
            @@frm_cobertura_madre = $datagrid_cober['grd_cob_madre'];
            $iaux='true';
        }
    }
    $frm_cobertura_madre = @@frm_cobertura_madre;
    //codigo de la tabla
    $sql = "SELECT CAMPO1, DESCRIPCION, VALOR FROM ADMIN_CATALOGOS WHERE COD_CATALOGO = 'COBERTURA_MADRE' AND PRO_UID = '$pro_uid' AND ESTADO = 1 AND CODIGO = $frm_cobertura_madre ";
    $rs = executeQuery($sql, $cnx);
    @@tri_rango_cobertura = ($rs['1']['CAMPO1'] == '' ? 0 : $rs['1']['CAMPO1']);
    $tri_valor_cobertura_madre = ($rs['1']['VALOR'] == '' ? 18 : $rs['1']['VALOR']);
    @@frm_cobertura_madre_label = $rs['1']['DESCRIPCION'];

    @@tri_peso_caso = @#tri_rango_cobertura + @#tri_rango_poliza + @#tri_rango_monto;

    //fecha de respuesta
    @@frm_fecha_notificacion = date('Y-m-d');
    $fecha_notificacion = @@frm_fecha_notificacion;
    $dias_respuesta = @@frm_dias_respuesta;

    $date_actual = date('Y-m-d');

    $date_respuesta = date("Y-m-d",strtotime($fecha_notificacion."+ $dias_respuesta days"));

    @@frm_fecha_respuesta = $date_respuesta;

    //para el tiempo de la poliza
    @@frm_fecha_ingreso_poliza_aux = (@@frm_fecha_ingreso_poliza_aux == '' ? @@frm_fecha_ingreso_poliza : @@frm_fecha_ingreso_poliza_aux);
    $date_poliza = explode(" ",@@frm_fecha_ingreso_poliza_aux);
    $arr_date_poliza = explode("/",$date_poliza[0]);
    $mes_pol = $arr_date_poliza[0];
    $dia_pol = $arr_date_poliza[1];
    $anio_pol = $arr_date_poliza[2];

    //@@frm_fecha_ingreso_poliza = substr(@@frm_fecha_ingreso_poliza, 0, 10);
    //@@frm_fecha_ingreso_poliza = str_replace("/","-",@@frm_fecha_ingreso_poliza);
    @@frm_fecha_ingreso_poliza = $anio_pol.'-'.$mes_pol.'-'.$dia_pol;
    $firstDate = date("Y-m-d", strtotime(@@frm_fecha_ingreso_poliza));
    //formatDate(@@frm_fecha_ingreso_polizass, "yyyy-mm-dd");
    $secondDate = date("Y-m-d");
    $dateDifference = abs(strtotime($secondDate) - strtotime($firstDate));

    $years  = floor($dateDifference / (365 * 60 * 60 * 24));
    $months = floor(($dateDifference - $years * 365 * 60 * 60 * 24) / (30 * 60 * 60 * 24));
    $days   = floor(($dateDifference - $years * 365 * 60 * 60 * 24 - $months * 30 * 60 * 60 *24) / (60 * 60 * 24));

    $time = $years." años,  ".$months." meses y ".$days." días";

    @@frm_tiempo_poliza = $time;

    //tipo de solicitud catalogo
    $sql_ts = "SELECT CODIGO FROM ADMIN_CATALOGOS WHERE COD_CATALOGO = 'TIPO_SINIESTRO' AND PRO_UID = '$pro_uid' AND ESTADO = 1 AND CODIGO = $tri_valor_cobertura_madre ";
    $rs_ts = executeQuery($sql_ts, $cnx);
    @@frm_tipo_siniestro = $rs_ts['1']['CODIGO'];

    if(@@frm_accion == 'CONTINUAR' || @@frm_accion == 'ESPERAR')
    {
        if(@@tri_bandera_alcance == 'ALCANCE'){
            //GENERAR ALCANCE EN SISE
            $codigo_cau = @@frm_causa_siniestro;
            $sql_ca = "SELECT CODIGO, CONCAT(VALOR, ' ', DESCRIPCION) AS NOMBRE FROM ADMIN_CATALOGOS WHERE COD_CATALOGO = 'CAUSAS_SINIESTROS' AND CODIGO = '$codigo_cau'";
            $rs_ca = executeQuery($sql_ca, $cnx);
            @@frm_causa_siniestro_label = $rs_ca['1']['NOMBRE'];

            //header
            $cod_suc = @@frm_sucursal;
            $cod_ramo = @@frm_ramo;
            $id_pv_fact = @@frm_id_pv;
            $id_pv_cero = @@frm_id_pv_cero;
            $fec_hora_reclamo = @@frm_fecha_ocurrencia;
            $fec_aviso = @@frm_fecha_notificacion;
            $fec_registro = date('Y-m-d');
            $fec_dciapol = date('Y-m-d');
            $nro_dcia = "";
            $cod_causa = @@frm_causa_siniestro;
            $cod_usuario = 'iportilla';
            $cod_evento = 1;
            $cod_causa_stro = 0;
            $cod_tipo_pago = (@@frm_tipo_pago == '' ? 0: @@frm_tipo_pago);
            $nro_crm = @@APP_NUMBER;
            $cod_tipo_siniestro = @@frm_tipo_siniestro;
            $imp_monto_reportado = @@frm_monto_reportado;
            $sn_mes_vencido = (@@frm_mes_vencido_label == 'true' ? 1 : 0);
            $cod_cobertura_madre = @@frm_cobertura_madre;
            //$cod_diagnostico = (@@frm_diagnostico == '' ? 0 : @@frm_diagnostico);
            $cod_diagnostico = 0;
            $cod_motivo_detenido = 1;
            $cod_usuario_autoriza = "DSAA";
            $fec_concesion_credito = (@@frm_fecha_concesion == '' ? '1999-01-01' : @@frm_fecha_concesion);
            $fec_vencimiento_credito = (@@frm_fecha_vencimiento == '' ? '1999-01-01' : @@frm_fecha_vencimiento);
            $cod_plazo_credito = (@@frm_plazo_credito == '' ? 0 : @@frm_plazo_credito);
            $cod_aseg = @@frm_cod_aseg;

            $imp_estimado = @#frm_monto_reportado + @#frm_monto_pagado_al;
            $id_stro = @@tri_id_stro;
            $nro_stro = @@tri_nro_stro;
            $cod_estado_siniestro= 1;
            $cod_estado_evento = 7;
            $marca_stro = 1;
            $imp_recl = 0;

            //obtengo el token
            $sql_cata_auth = "SELECT DESCRIPCION FROM ADMIN_CATALOGOS WHERE PRO_UID = '$pro_uid' AND CODIGO = 'URL_CU_GEN_TOKEN_AUTH'";
            $rs_auth =  executeQuery($sql_cata_auth, $cnx);

            $url_auth = isset($rs_auth['1']['DESCRIPCION']) ? $rs_auth['1']['DESCRIPCION'] : '';
            $dns_auth = $url_auth;

            $aVars_auth = array(
                "userName" => "servicio_proveedores",
                "password" => "BQFkJJsh1;0VsHOS48y8"
            );

            $json_auth = json_encode($aVars_auth);

            $ch_auth = curl_init();
            curl_setopt($ch_auth, CURLOPT_URL, $dns_auth);
            curl_setopt($ch_auth, CURLOPT_CUSTOMREQUEST, "POST");
            curl_setopt($ch_auth, CURLOPT_POSTFIELDS, $json_auth);
            curl_setopt($ch_auth, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($ch_auth, CURLOPT_FAILONERROR, true);
            curl_setopt($ch_auth, CURLOPT_HTTPHEADER,
            array(
                "Accept: application/json",
                "Content-Type: application/json",
                "Accept-Language: application/json"
            )
        );
        $res_auth = curl_exec($ch_auth);
        $msg_m_auth = '';
        if(curl_errno($ch_auth)){
            $msg_m_auth = curl_error($ch_auth);
            //tarea 2
            @@tri_message_grabado = $msg_m_auth;
            @@envio_mail = PMFSendMessage(@@APPLICATION,$de,$para, $cc, $bcc, $asunto, $plantilla_rec, array('texto' => $texto));
        }
        curl_close($ch_auth);
        $rs_m_auth = json_decode($res_auth, true);

        PMFBitacoraServicios(@@APP_NUMBER, 'trigger', 'CUSW-S-276', $dns_auth, 'POST', 'Authorization', $json_auth, $rs_m_auth, $msg_m_auth);

        $token='';
        try
        {
            if(count($rs_m_auth) > 0 && !empty($rs_m_auth)){
                foreach($rs_m_auth as $key => $data_auth){
                    if($key == 'Token'){
                        $token = $data_auth;
                    }
                }
            }
        }
        catch(Exception $e)
        {
            @@tri_message_grabado = $msg_m_auth;
            @@envio_mail = PMFSendMessage(@@APPLICATION,$de,$para, $cc, $bcc, $asunto, $plantilla_rec, array('texto' => $texto));
        }

        $sql_cata = "SELECT DESCRIPCION FROM ADMIN_CATALOGOS WHERE PRO_UID = '$pro_uid' AND COD_CATALOGO = 'SERVICIOS_WEB_S' AND CODIGO = 'GRABAR_SINIESTRO'";
        $rs =  executeQuery($sql_cata, $cnx);
        $url = isset($rs['1']['DESCRIPCION']) ? $rs['1']['DESCRIPCION'] : '';
        $dns = $url;

        $header_stro['siniestro']["cabecera_siniestro"] = array(
            "cod_suc" => $cod_suc,
            "cod_ramo" => $cod_ramo,
            "id_pv_fact" => $id_pv_fact,
            "id_pv_cero" => $id_pv_cero,
            "fec_hora_reclamo" => $fec_hora_reclamo,
            "fec_aviso" => $fec_aviso,
            "fec_registro" => $fec_registro,
            "fec_dciapol" => $fec_dciapol,
            "nro_dcia" => $nro_dcia,
            "cod_causa" => $cod_causa,
            "cod_usuario" => $cod_usuario,
            "cod_evento" => $cod_evento,
            "cod_causa_stro" => $cod_causa_stro,
            "cod_tipo_pago" => $cod_tipo_pago,
            "nro_crm" => $nro_crm,
            "cod_tipo_siniestro" => $cod_tipo_siniestro,
            "imp_monto_reportado" => $imp_monto_reportado,
            "sn_mes_vencido" => $sn_mes_vencido,
            "cod_cobertura_madre" => $cod_cobertura_madre,
            "cod_diagnostico" => $cod_diagnostico,
            "cod_motivo_detenido" => $cod_motivo_detenido,
            "cod_usuario_autoriza" => $cod_usuario_autoriza,
            "fec_concesion_credito" => $fec_concesion_credito,
            "fec_vencimiento_credito" => $fec_vencimiento_credito,
            "cod_plazo_credito" => $cod_plazo_credito,
            "cod_aseg" => $cod_aseg,
            "nro_casoBpm" => $nro_crm,
            "id_stro" => $id_stro,
            "marca_stro" => $marca_stro
        );

        //detalle_cobertura
        if(@@grd_coberturas['1']['grd_txt_desc_riesgo'] != '' ){
            $i=1;
            foreach(@=grd_coberturas as $datagrid_cober){
                if($datagrid_cober['grd_txt_aplicar'] == 'SI' && $datagrid_cober['grd_txt_alcance'] == 'SI' && $datagrid_cober['grd_txt_valor'] != ''){
                    $cod_ramo_tec = $datagrid_cober['grd_cod_ramo_tec'];
                    $cod_subramo = $datagrid_cober['grd_cod_subramo_tec'];
                    $ind_riesgo = $datagrid_cober['grd_ind_riesgo'];
                    $cod_riesgo = $datagrid_cober['grd_cod_riesgo'];
                    $cod_objeto = $datagrid_cober['grd_cod_objeto'];
                    $cod_amparo = $datagrid_cober['grd_cod_amparo'];
                    $cod_categ = $datagrid_cober['grd_cod_categ'];
                    $cod_tercero = $datagrid_cober['grd_cod_tercero'];
                    $cod_aseg = $datagrid_cober['grd_cod_aseg'];
                    $nro_aseg = $datagrid_cober['grd_nro_aseg'];
                    $nro_pariente = $datagrid_cober['grd_nro_pariente'];

                    $header_stro['siniestro']['aseguradoStro']['detalle_cobertura'] = array(array(
                        "cod_ramo_tec" => $cod_ramo_tec,
                        "cod_subramo" => $cod_subramo,
                        "ind_riesgo" => $ind_riesgo,
                        "cod_riesgo" => $cod_riesgo,
                        "cod_objeto" => $cod_objeto,
                        "cod_amparo" => $cod_amparo,
                        "cod_categ" => $cod_categ,
                        "cod_tercero" => $cod_tercero,
                        "cod_aseg" => $cod_aseg,
                        "nro_aseg" => $nro_aseg,
                        "nro_pariente" => $nro_pariente,
                        "imp_estimado" => $imp_estimado,
                        "cod_estado_siniestro" => $cod_estado_siniestro,
                        "cod_estado_evento" => $cod_estado_evento,
                        "imp_recl" => $imp_recl)
                    );
                }
                $i++;
            }
        }
        if(@@grd_beneficiarios['1']['grd_codigo_b'] != '' ){
            foreach(@=grd_beneficiarios as $datagrid){
                $nro_beneficiario = $datagrid['nro_benef'];
                $cod_parentesco = $datagrid['cod_parentesco'];
                $txt_apellido1 = $datagrid['txt_apellido1'];
                $txt_apellido2 = $datagrid['txt_apellido2'];
                $txt_nombre = $datagrid['txt_nombre'];
                $cod_leyenda = $datagrid['cod_leyenda'];
                $pje_partic = $datagrid['pje_partic'];
                $cod_tipo_doc = $datagrid['cod_tipo_doc'];
                $txt_documento = $datagrid['txt_documento'];
                $cod_tipo_persona = $datagrid['cod_tipo_persona'];

                $header_stro['siniestro']['aseguradoStro']['beneficiariosStro'] = array(array(
                    "nro_benef" => $nro_beneficiario,
                    "cod_parentesco" => $cod_parentesco,
                    "txt_apellido1" => $txt_apellido1,
                    "txt_apellido2" => $txt_apellido2,
                    "txt_nombre" => $txt_nombre,
                    "cod_leyenda" => $cod_leyenda,
                    "pje_partic" => $pje_partic,
                    "cod_tipo_doc" => $cod_tipo_doc,
                    "txt_documento" => $txt_documento,
                    "cod_tipo_persona" => $cod_tipo_persona)
                );
            }
        }
        if(@@frm_tipo_asegurado == 'O'){

            $nro_doc = @@frm_documento_fallecido;
            $cod_tipo_doc = @@frm_tipo_documento_fallecido;
            $txt_apellido1 = @@frm_apellido_paterno_fallecido;
            $txt_apellido2 = @@frm_apellido_materno_fallecido;
            $txt_nombre = @@frm_nombres_fallecido;
            $cod_parentezco_stro = @@frm_parentesco_fallecido;

            $header_stro['siniestro']['aseguradoStro']['dependienteStro'] = array(array(
                "nro_doc" => $nro_doc,
                "cod_tipo_doc" => $cod_tipo_doc,
                "txt_apellido1" => $txt_apellido1,
                "txt_apellido2" => $txt_apellido2,
                "txt_nombre" => $txt_nombre,
                "cod_parentezco_stro" => $cod_parentezco_stro)
            );
        }

        $json_stro = json_encode($header_stro);
        @@send_json_al = $json_stro;
        try{

            $ch = curl_init();
            curl_setopt($ch, CURLOPT_URL, $dns);
            curl_setopt($ch, CURLOPT_POST, true);
            curl_setopt($ch, CURLOPT_POSTFIELDS, $json_stro);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($ch, CURLOPT_HTTPHEADER,
            array(
                "Accept: application/json",
                "Content-Type: application/json",
                "Accept-Language: application/json",
                "Authorization: Bearer ". $token
            )
        );

        $res = curl_exec($ch);

        if(curl_errno($ch)){
            $msg_m = curl_error($ch);
        }
        curl_close($ch);

        $result = json_decode($res);


          PMFBitacoraServicios(@@APP_NUMBER, 'trigger', 'CUSW-443', $dns, 'POST', "Authorization", json_encode($json_stro), json_encode($result), json_encode($msg_m));


        @@result_update = $result;

        if(isset($result->isError) && $result->isError === false && isset($result->errorNumber) && $result->errorNumber == 0)
        {
            @@tri_id_stro_al = $result->id_stro;
            @@tri_nro_stro_al = $result->nro_stro;
            @@tri_bandera_update_al = 'true';
        }else{
            @@tri_message_update_al = $result->Message;
            @@tri_message_grabado = $msg_m_auth;
            @@envio_mail = PMFSendMessage(@@APPLICATION,$de,$para, $cc, $bcc, $asunto, $plantilla_rec, array('texto' => $texto));

        }

    }catch(Exception $e)
    {
        $result['mensaje'] = 'false';
        @@tri_message_update_al = 'ExcepciÃƒÂ³n capturada: Error al consultar la Base de Datos, comuniquese con el administrador.- '.$e->getMessage();
        //tarea 2
        @@tri_message_grabado = $msg_m_auth;
        @@envio_mail = PMFSendMessage(@@APPLICATION,$de,$para, $cc, $bcc, $asunto, $plantilla_rec, array('texto' => $texto));
    }
}else{
    //GENERAR RESERVA EN SISE
    //header
    $cod_suc = @@frm_sucursal;
    $cod_ramo = @@frm_ramo;
    $id_pv_fact = @@frm_id_pv;
    $id_pv_cero = @@frm_id_pv_cero;
    $fec_hora_reclamo = @@frm_fecha_ocurrencia;
    $fec_aviso = @@frm_fecha_notificacion;
    $fec_registro = date('Y-m-d');
    $fec_dciapol = date('Y-m-d');
    $nro_dcia = "";
    $cod_causa = @@frm_causa_siniestro;
    //$cod_usuario = @@USR_USERNAME;
    $cod_usuario = 'iportilla';
    $cod_evento = 1;
    $cod_causa_stro = 0;
    $cod_tipo_pago = (@@frm_tipo_pago == '' ? 0: @@frm_tipo_pago);
    $nro_crm = @@APP_NUMBER;
    $cod_tipo_siniestro = @@frm_tipo_siniestro;
    $imp_monto_reportado = @@frm_monto_reportado;
    $sn_mes_vencido = (@@frm_mes_vencido_label == 'true' ? -1 : 0);
    $cod_cobertura_madre = @@frm_cobertura_madre;
    $cod_diagnostico = (@@frm_diagnostico == '' ? 0 : @@frm_diagnostico);
    $cod_motivo_detenido = 1;
    $cod_usuario_autoriza = "DSAA";
    $fec_concesion_credito = (@@frm_fecha_concesion == '' ? '1999-01-01' : @@frm_fecha_concesion);
    $fec_vencimiento_credito = (@@frm_fecha_vencimiento == '' ? '1999-01-01' : @@frm_fecha_vencimiento);
    $cod_plazo_credito = (@@frm_plazo_credito == '' ? 0 : @@frm_plazo_credito);
    $cod_aseg = @@frm_cod_aseg;

    //detalle_cobertura
    $cod_ramo_tec = @@frm_cod_ramo_tec;
    $cod_subramo = @@frm_cod_subramo_tec;
    $ind_riesgo = @@frm_ind_riesgo;
    $cod_riesgo = @@frm_cod_riesgo;
    $cod_objeto = @@frm_cod_objeto;
    $cod_amparo = @@frm_cod_amparo;
    $cod_categ = @@frm_cod_categ;
    $cod_tercero = @@frm_cod_tercero;
    $cod_aseg = @@frm_cod_aseg;
    $nro_aseg = @@frm_nro_aseg;
    $nro_pariente = @@frm_nro_pariente;
    $imp_estimado = @@frm_monto_reportado;
    $cod_estado_siniestro= 1;
    $cod_estado_evento = 1;
    $imp_recl = 0;

    //obtengo el token
    $sql_cata_auth = "SELECT DESCRIPCION FROM ADMIN_CATALOGOS WHERE PRO_UID = '$pro_uid' AND CODIGO = 'URL_CU_GEN_TOKEN_AUTH'";
    $rs_auth =  executeQuery($sql_cata_auth, $cnx);

    $url_auth = isset($rs_auth['1']['DESCRIPCION']) ? $rs_auth['1']['DESCRIPCION'] : '';
    $dns_auth = $url_auth;

    $aVars_auth = array(
        "userName" => "servicio_proveedores",
        "password" => "BQFkJJsh1;0VsHOS48y8"
    );

    $json_auth = json_encode($aVars_auth);

    $ch_auth = curl_init();
    curl_setopt($ch_auth, CURLOPT_URL, $dns_auth);
    curl_setopt($ch_auth, CURLOPT_CUSTOMREQUEST, "POST");
    curl_setopt($ch_auth, CURLOPT_POSTFIELDS, $json_auth);
    curl_setopt($ch_auth, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch_auth, CURLOPT_FAILONERROR, true);
    curl_setopt($ch_auth, CURLOPT_HTTPHEADER,
    array(
        "Accept: application/json",
        "Content-Type: application/json",
        "Accept-Language: application/json"
    )
);
$res_auth = curl_exec($ch_auth);
if(curl_errno($ch_auth)){
    $msg_m_auth = curl_error($ch_auth);
    @@tri_message_grabado = $msg_m_auth;
    @@envio_mail = PMFSendMessage(@@APPLICATION,$de,$para, $cc, $bcc, $asunto, $plantilla_rec, array('texto' => $texto));
}
curl_close($ch_auth);
$rs_m_auth = json_decode($res_auth,true);



$token='';
try
{
    if(count($rs_m_auth) > 0 && !empty($rs_m_auth)){
        foreach($rs_m_auth as $key => $data_auth){
            if($key == 'Token'){
                $token = $data_auth;
            }
        }
    }
}
catch(Exception $e)
{
    @@tri_message_grabado = $result->Message;
    @@envio_mail = PMFSendMessage(@@APPLICATION,$de,$para, $cc, $bcc, $asunto, $plantilla_rec, array('texto' => $texto));
}


$sql_cata = "SELECT DESCRIPCION FROM ADMIN_CATALOGOS WHERE PRO_UID = '$pro_uid' AND COD_CATALOGO = 'SERVICIOS_WEB_S' AND CODIGO = 'GRABAR_SINIESTRO'";
$rs =  executeQuery($sql_cata, $cnx);
$url = isset($rs['1']['DESCRIPCION']) ? $rs['1']['DESCRIPCION'] : '';
$dns = $url;

$header_stro['siniestro']["cabecera_siniestro"] = array(
    "cod_suc" => $cod_suc,
    "cod_ramo" => $cod_ramo,
    "id_pv_fact" => $id_pv_fact,
    "id_pv_cero" => $id_pv_cero,
    "fec_hora_reclamo" => $fec_hora_reclamo,
    "fec_aviso" => $fec_aviso,
    "fec_registro" => $fec_registro,
    "fec_dciapol" => $fec_dciapol,
    "nro_dcia" => $nro_dcia,
    "cod_causa" => $cod_causa,
    "cod_usuario" => $cod_usuario,
    "cod_evento" => $cod_evento,
    "cod_causa_stro" => $cod_causa_stro,
    "cod_tipo_pago" => $cod_tipo_pago,
    "nro_crm" => $nro_crm,
    "cod_tipo_siniestro" => $cod_tipo_siniestro,
    "imp_monto_reportado" => $imp_monto_reportado,
    "sn_mes_vencido" => $sn_mes_vencido,
    "cod_cobertura_madre" => $cod_cobertura_madre,
    "cod_diagnostico" => $cod_diagnostico,
    "cod_motivo_detenido" => $cod_motivo_detenido,
    "cod_usuario_autoriza" => $cod_usuario_autoriza,
    "fec_concesion_credito" => $fec_concesion_credito,
    "fec_vencimiento_credito" => $fec_vencimiento_credito,
    "cod_plazo_credito" => $cod_plazo_credito,
    "cod_aseg" => $cod_aseg,
    "nro_casoBpm" => $nro_crm
);

if(@@grd_coberturas['1']['grd_txt_desc_riesgo'] != '' ){
    $i=1;
    $j=1;
    foreach(@=grd_coberturas as $datagrid_cober){
        if($datagrid_cober['grd_txt_aplicar'] == 'SI' && $datagrid_cober['grd_txt_valor'] != ''){
            $cod_ramo_tec = $datagrid_cober['grd_cod_ramo_tec'];
            $cod_subramo = $datagrid_cober['grd_cod_subramo_tec'];
            $ind_riesgo = $datagrid_cober['grd_ind_riesgo'];
            $cod_riesgo = $datagrid_cober['grd_cod_riesgo'];
            $cod_objeto = $datagrid_cober['grd_cod_objeto'];
            $cod_amparo = $datagrid_cober['grd_cod_amparo'];
            $cod_categ = $datagrid_cober['grd_cod_categ'];
            $cod_tercero = $datagrid_cober['grd_cod_tercero'];
            $cod_aseg = $datagrid_cober['grd_cod_aseg'];
            $nro_aseg = $datagrid_cober['grd_nro_aseg'];
            $nro_pariente = $datagrid_cober['grd_nro_pariente'];
            $imp_estimado = $datagrid_cober['grd_txt_valor'];

            if($j == 1){
                $header_stro['siniestro']['aseguradoStro']['detalle_cobertura'] = array(array(
                    "cod_ramo_tec" => $cod_ramo_tec,
                    "cod_subramo" => $cod_subramo,
                    "ind_riesgo" => $ind_riesgo,
                    "cod_riesgo" => $cod_riesgo,
                    "cod_objeto" => $cod_objeto,
                    "cod_amparo" => $cod_amparo,
                    "cod_categ" => $cod_categ,
                    "cod_tercero" => $cod_tercero,
                    "cod_aseg" => $cod_aseg,
                    "nro_aseg" => $nro_aseg,
                    "nro_pariente" => $nro_pariente,
                    "imp_estimado" => $imp_estimado,
                    "cod_estado_siniestro" => $cod_estado_siniestro,
                    "cod_estado_evento" => $cod_estado_evento,
                    "imp_recl" => $imp_recl)
                );
                $j++;
            }else{
                $header_stro_cober = array(
                    "cod_ramo_tec" => $cod_ramo_tec,
                    "cod_subramo" => $cod_subramo,
                    "ind_riesgo" => $ind_riesgo,
                    "cod_riesgo" => $cod_riesgo,
                    "cod_objeto" => $cod_objeto,
                    "cod_amparo" => $cod_amparo,
                    "cod_categ" => $cod_categ,
                    "cod_tercero" => $cod_tercero,
                    "cod_aseg" => $cod_aseg,
                    "nro_aseg" => $nro_aseg,
                    "nro_pariente" => $nro_pariente,
                    "imp_estimado" => $imp_estimado,
                    "cod_estado_siniestro" => $cod_estado_siniestro,
                    "cod_estado_evento" => $cod_estado_evento,
                    "imp_recl" => $imp_recl);
                    array_push($header_stro['siniestro']['aseguradoStro']['detalle_cobertura'],$header_stro_cober);
                }
            }
            $i++;
        }
    }
    //print_r($header_stro);
    if(@@grd_beneficiarios['1']['grd_codigo_b'] != '' ){
        foreach(@=grd_beneficiarios as $datagrid){
            $nro_beneficiario = $datagrid['nro_benef'];
            $cod_parentesco = $datagrid['cod_parentesco'];
            $txt_apellido1 = $datagrid['txt_apellido1'];
            $txt_apellido2 = $datagrid['txt_apellido2'];
            $txt_nombre = $datagrid['txt_nombre'];
            $cod_leyenda = $datagrid['cod_leyenda'];
            $pje_partic = $datagrid['pje_partic'];
            $cod_tipo_doc = $datagrid['cod_tipo_doc'];
            $txt_documento = $datagrid['txt_documento'];
            $cod_tipo_persona = $datagrid['cod_tipo_persona'];

            $header_stro['siniestro']['aseguradoStro']['beneficiariosStro'] = array(array(
                "nro_benef" => $nro_beneficiario,
                "cod_parentesco" => $cod_parentesco,
                "txt_apellido1" => $txt_apellido1,
                "txt_apellido2" => $txt_apellido2,
                "txt_nombre" => $txt_nombre,
                "cod_leyenda" => $cod_leyenda,
                "pje_partic" => $pje_partic,
                "cod_tipo_doc" => $cod_tipo_doc,
                "txt_documento" => $txt_documento,
                "cod_tipo_persona" => $cod_tipo_persona)
            );
        }
    }
    if(@@frm_tipo_asegurado == 'O'){

        $nro_doc = @@frm_documento_fallecido;
        $cod_tipo_doc = @@frm_tipo_documento_fallecido;
        $txt_apellido1 = @@frm_apellido_paterno_fallecido;
        $txt_apellido2 = @@frm_apellido_materno_fallecido;
        $txt_nombre = @@frm_nombres_fallecido;
        $cod_parentezco_stro = @@frm_parentesco_fallecido;

        $header_stro['siniestro']['aseguradoStro']['dependienteStro'] = array(array(
            "nro_doc" => $nro_doc,
            "cod_tipo_doc" => $cod_tipo_doc,
            "txt_apellido1" => $txt_apellido1,
            "txt_apellido2" => $txt_apellido2,
            "txt_nombre" => $txt_nombre,
            "cod_parentezco_stro" => $cod_parentezco_stro)
        );
    }

    $json_stro = json_encode($header_stro);
    @@send_json = $json_stro;

    //print_r($json_stro);
    //die();

    try{

        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $dns);
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $json_stro);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_HTTPHEADER,
        array(
            "Accept: application/json",
            "Content-Type: application/json",
            "Accept-Language: application/json",
            "Authorization: Bearer ". $token
        )
    );

    $res = curl_exec($ch);

    //bitacora
     $msg_m = '';
    if(curl_errno($ch)){
        $msg_m = curl_error($ch);
    }
    curl_close($ch);

        PMFBitacoraServicios(@@APP_NUMBER, 'trigger', 'CUSW-744', $dns, 'POST', "Authorization", json_encode($json_stro), json_encode($result), json_encode($msg_m));


    $result = json_decode($res);

    @@result_grabado = $result;


    if(isset($result->isError) && $result->isError === false && isset($result->errorNumber) && $result->errorNumber == 0)
    {
        @@tri_id_stro = $result->id_stro;
        @@tri_nro_stro = $result->nro_stro;
        @@tri_bandera_grabado = 'true';
        @@frm_fecha_reserva = date('Y-m-d');
    }else{
        @@tri_message_grabado = $result->Message;
        @@envio_mail = PMFSendMessage(@@APPLICATION,$de,$para, $cc, $bcc, $asunto, $plantilla_rec, array('texto' => $texto));
    }

}catch(Exception $e)
{
    @@tri_message_grabado = $result->Message;
    @@envio_mail = PMFSendMessage(@@APPLICATION,$de,$para, $cc, $bcc, $asunto, $plantilla_rec, array('texto' => $texto));

}
}
//	print_r($result);
}

} catch (Exception $e) {

    $errorMessage =  $e->getMessage();

}
