<?php
/*******************************************************
 *
 * Generated by ProcessMaker Trigger Wizard
 * Library: ProcessMaker Functions
 * Method: PMF Send Message
 * Date: 2020-08-30 10:35:06
 *
 * ProcessMaker 2020
 *
 *******************************************************/
try{
$cnx = "11264850561d723f004d5c2072943786";
$app_uid        = @@APPLICATION;
$pro_uid        = @@PROCESS;

$texto = '';

//ENVIO DE EMAIL
	
$de = '';
//$de = 'Seguros Equinoccial Venta Virtual<infoequivida@segurosequinoccial.com>';

//monto reservado
$monto_liquidar = @@frm_monto_reportado;

//codigo de la tabla
$sql = "SELECT CAMPO2 FROM ADMIN_CATALOGOS WHERE COD_CATALOGO = 'APROBADORES_PDA' AND PRO_UID = '$pro_uid' AND ESTADO = 1 AND VALOR <= $monto_liquidar AND INTEGRACION > $monto_liquidar ";
$rs = executeQuery($sql, $cnx);


$para = ($rs['1']['CAMPO2'] == 'usuario' ? @@tri_user_auditor_mail : $rs['1']['CAMPO2']);

$cc = @@tri_user_auditor_mail;
$bcc=''; 
$asunto = "Creación de reserva de SINIESTRO ". @#APP_NUMBER;
	
$plantilla_rec = 'Creacion_Reserva.html';

if(@@tri_nro_stro != ''){
	@@envio_mail = PMFSendMessage(@@APPLICATION,$de,$para, $cc, $bcc, $asunto, $plantilla_rec, array('texto' => $texto));
}

 } catch (Exception $e) {
	
	$errorMessage =  $e->getMessage();
	
 
}