<?php
/*******************************************************
 *
 * Generated by ProcessMaker Trigger Wizard
 * Library: ProcessMaker Functions
 * Method: PMF Send Message
 * Date: 2020-08-30 10:35:06
 *
 * ProcessMaker 2020
 * cambios
 *******************************************************/
try {
    $texto = 'Falta de documentos SINIESTRO';

    //ENVIO DE EMAIL
    $de = '';
    //$de = 'Seguros Equinoccial Venta Virtual<infoequivida@segurosequinoccial.com>';

    $para = @@frm_asegurado_mail;
    $cc = @@tri_user_sac_mail;
    $bcc = '';
    $asunto = "Notificación Falta de documentos SINIESTRO " . @#APP_NUMBER;

    $plantilla_rec = 'Adjuntar_Documento_Faltante.html';
    @@envio_mail = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('texto' => $texto));


    @@tri_bandera_docs = 'true';
} catch (Exception $e) {

    $errorMessage =  $e->getMessage();
}
