<?php
/*******************************************************
 *
 * Generated by ProcessMaker Trigger Wizard
 * Library: ProcessMaker Functions
 * Method: PMF Send Message
 * Date: 2020-08-30 10:35:06
 *
 * ProcessMaker 2020
 *
 *******************************************************/
try {
    $texto = 'Creación de ticket de SINIESTRO';

    //ENVIO DE EMAIL
    $de = '';
    //$de = 'Seguros Equinoccial Venta Virtual<infoequivida@segurosequinoccial.com>';

    $para = @@frm_asegurado_mail;

    $cc = @@tri_user_sac_mail;
    $bcc = '';
    $asunto = "Creación de ticket de SINIESTRO " . @#APP_NUMBER;

    $plantilla_rec = 'Creacion_caso.html';
    @@envio_mail = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('texto' => $texto));
} catch (Exception $e) {

    $errorMessage =  $e->getMessage();
}
