<?php
/*******************************************************
 *
 * Generated by ProcessMaker Trigger Wizard
 * Library: ProcessMaker Functions
 * Method: PMF Send Message
 * Date: 2020-08-30 10:35:06
 *
 * ProcessMaker 2020
 *
 *******************************************************/
try {
    $cnx = "11264850561d723f004d5c2072943786";
    $app_uid        = @@APPLICATION;
    $pro_uid        = @@PROCESS;

    $texto = 'Notificación de SINIESTRO';
    //ENVIO DE EMAIL

    $de = '';
    //$de = 'Seguros Equinoccial Venta Virtual<infoequivida@segurosequinoccial.com>';

    $para = @@frm_asegurado_mail;

    $cc = @@frm_asegurado_mail_1;
    $bcc = '';
    $asunto = "Notificación de SINIESTRO " . @#APP_NUMBER;

    $plantilla_rec = 'No_procede.html';

    if (@@tri_nro_stro != '') {
        @@envio_mail = PMFSendMessage(@@APPLICATION, $de, $para, $cc, $bcc, $asunto, $plantilla_rec, array('texto' => $texto));
    }
} catch (Exception $e) {

    $errorMessage =  $e->getMessage();
}
